[Config]
GOVERLAY_MANGOHUD=1
GOVERLAY_VKBASALT=0
GOVERLAY_OPTISCALER=0
GOVERLAY_TWEAKS=1
DLL=dxgi.dll
PRESERVE_INI=true

[Env]
PROTON_ENABLE_HDR=1
ENABLE_HDR_WSI=1
PROTON_ENABLE_WAYLAND=1

[Launchers]
Cyberpunk 2077 = REDprelauncher.exe|bin/x64/Cyberpunk2077.exe
Witcher 3 = REDprelauncher.exe|bin/x64_dx12/witcher3.exe
Baldurs Gate 3 = Launcher/LariLauncher.exe|bin/bg3_dx11.exe
Baldurs Gate 3 Alt = Launcher\LariLauncher.exe|bin/bg3_dx11.exe
HITMAN 3 = Launcher.exe|Retail/HITMAN3.exe
HITMAN World of Assassination = Launcher.exe|Retail/HITMAN3.exe
SYNCED = Launcher/sop_launcher.exe|SYNCED.exe
2KLauncher = 2KLauncher/LauncherPatcher.exe|DoesntMatter.exe
Warhammer 40,000 DARKTIDE = launcher/Launcher.exe|binaries/Darktide.exe
Warhammer Vermintide 2 = launcher/Launcher.exe|binaries_dx12/vermintide2_dx12.exe
Satisfactory = FactoryGameSteam.exe|Engine/Binaries/Win64/FactoryGameSteam-Win64-Shipping.exe
FINAL FANTASY XIV Online = boot/ffxivboot.exe|game/ffxiv_dx11.exe
DuneAwakening = Launcher/FuncomLauncher.exe|DuneSandbox/Binaries/Win64/DuneSandbox-Win64-Shipping.exe
