unit overlay_config;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, IniFiles, FileUtil, configfile, configmanager, configkeys, bgmod_resources, optiscaler_update;

type
  TVkBasaltSettings = record
    BasaltFolder: string;
    BasaltCfgFile: string;
    Version: string;
    Channel: string;
    ToggleKey: string;
    CasPosition: Integer;
    FxaaPosition: Integer;
    SmaaPosition: Integer;
    DlsPosition: Integer;
    ReshadeEffects: TStrings;
    ActiveGameName: string;
  end;

  TVkSumiSettings = record
    SumiFolder: string;
    SumiCfgFile: string;
    Version: string;
    Channel: string;
    Enabled: Boolean;
    ToggleKeys: string;
    TrackbarPositions: array[0..14] of Integer;
    ActiveGameName: string;
  end;

  TOptiScalerSettings = record
    ActiveGameName: string;
    Version: string;
    Channel: string;
    FilenameItemIndex: Integer;
    EmuFp8Checked: Boolean;
    ShortcutKey: string;
    MenuScalePosition: Integer;
    OverrideChecked: Boolean;
    SpoofChecked: Boolean;
    FsrversionItemIndex: Integer;
    OptipatcherChecked: Boolean;
    
    // FakeNvapi options
    ForceReflexChecked: Boolean;
    ReflexItemIndex: Integer;
    ForceLatencyFlexChecked: Boolean;
    LatencyFlexItemIndex: Integer;
    TraceLogChecked: Boolean;
  end;

function SanitizeFileName(const AName: string): string;
function GetGameConfigDir(const AGameName: string): string;

function SaveVkBasaltConfig(const Settings: TVkBasaltSettings; out ErrMsg: string): Boolean;
function SaveVkSumiConfig(const Settings: TVkSumiSettings; out ErrMsg: string): Boolean;
function SaveOptiScalerConfigCore(const Settings: TOptiScalerSettings; const EnvGamemodeRun, LaunchCommandSuffix: string; GeneralCheckbox1Checked, ActiveGameIsNonSteam, ActiveGameIsNonSteamLocal: Boolean; out ErrMsg: string; out LaunchCommand: string): Boolean;

implementation

function SanitizeFileName(const AName: string): string;
var
  i: Integer;
begin
  Result := AName;
  for i := 1 to Length(Result) do
    if Result[i] in ['/', '\', ':', '*', '?', '"', '<', '>', '|', ''''] then
      Result[i] := '_';
end;

function GetGameConfigDir(const AGameName: string): string;
begin
  Result := IncludeTrailingPathDelimiter(TConfigManager.GetHostDataDir) +
            'goverlay/gameconfig/' + SanitizeFileName(AGameName) + '/';
end;

function SaveVkBasaltConfig(const Settings: TVkBasaltSettings; out ErrMsg: string): Boolean;
var
  RepoDir, RelPath, EffectName, EffectKey, FullPath, EffectsLine: string;
  TexPath, IncPath: string;
  Lines: TStringList;
  Sharp: Double;
  FxaaQuality: Double;
  SmaaCorner: Double;
  DlsSharp: Double;
  FS: TFormatSettings;
  i: Integer;
  Ini: TIniFile;
  FGModFilePath: string;
begin
  Result := False;
  ErrMsg := '';

  if Settings.BasaltFolder = '' then
  begin
    ErrMsg := 'vkBasalt directory not found';
    Exit;
  end;

  RepoDir := IncludeTrailingPathDelimiter(Settings.BasaltFolder) + 'reshade-shaders';
  Lines := TStringList.Create;
  try
    Lines.Add('################### File Generated by Goverlay ' + Settings.Version + ' ' + Settings.Channel + ' ###################');
    Lines.Add('toggleKey = ' + Settings.ToggleKey);
    Lines.Add('enableOnLaunch = True');
    Lines.Add('');
    
    // --- create effects list" ---
    EffectsLine := '';
    // 1) CAS (if active)
    if Settings.CasPosition >= 1 then
      EffectsLine := EffectsLine + 'cas';
    // 2) FXAA (if active)
    if Settings.FxaaPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'fxaa';
    end;
    // 3) SMAA (if active)
    if Settings.SmaaPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'smaa';
    end;
    // 4) DLS (if active)
    if Settings.DlsPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'dls';
    end;
    // 5) reshade effects on the list
    if Assigned(Settings.ReshadeEffects) then
    begin
      for i := 0 to Settings.ReshadeEffects.Count - 1 do
      begin
        RelPath := Settings.ReshadeEffects[i];
        EffectName := ChangeFileExt(ExtractFileName(RelPath), '');
        if EffectsLine <> '' then
          EffectsLine := EffectsLine + ':';
        EffectsLine := EffectsLine + EffectName;
      end;
    end;
    if EffectsLine <> '' then
      Lines.Add('effects = ' + EffectsLine);
    Lines.Add('');
    
    // --- CAS adjustment if active ---
    if Settings.CasPosition >= 1 then
    begin
      Sharp := Settings.CasPosition / 10.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('casSharpness = ' + FloatToStrF(Sharp, ffFixed, 3, 1, FS));
    end;
    // --- FXAA adjustment if active ---
    if Settings.FxaaPosition >= 1 then
    begin
      FxaaQuality := Settings.FxaaPosition / 10.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('fxaaQualitySubpix = ' + FloatToStrF(FxaaQuality, ffFixed, 3, 1, FS));
    end;
    // --- SMAA adjustment if active ---
    if Settings.SmaaPosition >= 1 then
    begin
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      SmaaCorner := 25.0 * (Settings.SmaaPosition - 1) / 9.0;
      Lines.Add('smaaCornerRounding = ' + FloatToStrF(SmaaCorner, ffFixed, 3, 1, FS));
      Lines.Add('smaaThreshold = ' + FloatToStrF(0.1 - 0.05 * (Settings.SmaaPosition - 1) / 9.0, ffFixed, 3, 2, FS));
      Lines.Add('smaaMaxSearchSteps = ' + IntToStr(Round(16 + 16 * (Settings.SmaaPosition - 1) / 9.0)));
      Lines.Add('smaaMaxSearchStepsDiag = ' + IntToStr(Round(8 + 8 * (Settings.SmaaPosition - 1) / 9.0)));
    end;
    // --- DLS adjustment if active ---
    if Settings.DlsPosition >= 1 then
    begin
      DlsSharp := (Settings.DlsPosition - 1) / 9.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('dlsSharpness = ' + FloatToStrF(DlsSharp, ffFixed, 3, 1, FS));
    end;
    // --- Map reshade effects ---
    if Assigned(Settings.ReshadeEffects) then
    begin
      for i := 0 to Settings.ReshadeEffects.Count - 1 do
      begin
        RelPath := Settings.ReshadeEffects[i];
        EffectName := ChangeFileExt(ExtractFileName(RelPath), '');
        EffectKey := EffectName;
        FullPath := IncludeTrailingPathDelimiter(RepoDir) + RelPath;
        Lines.Add(EffectKey + ' = ' + FullPath);
      end;
    end;
    Lines.Add('');
    TexPath := IncludeTrailingPathDelimiter(RepoDir) + 'Textures';
    IncPath := IncludeTrailingPathDelimiter(RepoDir) + 'Shaders';
    Lines.Add('reshadeTexturePath = ' + TexPath);
    Lines.Add('reshadeIncludePath = ' + IncPath);
    
    // --- Save ---
    if not DirectoryExists(ExtractFileDir(Settings.BasaltCfgFile)) then
      ForceDirectories(ExtractFileDir(Settings.BasaltCfgFile));
    if FileExists(Settings.BasaltCfgFile) then
      DeleteFile(Settings.BasaltCfgFile);
    Lines.SaveToFile(Settings.BasaltCfgFile);

    // Update bgmod.conf with GOVERLAY_VKBASALT=1
    if Settings.ActiveGameName <> '' then
      FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
    else
      FGModFilePath := GetFGModPath + PathDelim + 'bgmod.conf';

    ForceDirectories(ExtractFilePath(FGModFilePath));
    Ini := TIniFile.Create(FGModFilePath);
    try
      Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '1');
    finally
      Ini.Free;
    end;

    Result := True;
  finally
    Lines.Free;
  end;
end;

function SaveVkSumiConfig(const Settings: TVkSumiSettings; out ErrMsg: string): Boolean;
const
  KEYS: array[0..14] of string = (
    'brightness', 'contrast', 'exposure', 'gamma',
    'saturation', 'vibrance', 'hue_deg', 'temperature', 'tint',
    'red_gain', 'green_gain', 'blue_gain',
    'shadows', 'midtones', 'highlights'
  );
var
  Lines: TStringList;
  FS: TFormatSettings;
  Val: Double;
  i: Integer;
  FGModFilePath: string;
  Ini: TIniFile;
begin
  Result := False;
  ErrMsg := '';
  
  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';

  Lines := TStringList.Create;
  try
    Lines.Add('################### File Generated by Goverlay ' + Settings.Version + ' ' + Settings.Channel + ' ###################');
    Lines.Add('# vkSumi color grading');
    Lines.Add('#');
    Lines.Add('# Lives at:');
    Lines.Add('#   ~/.config/vkSumi/vkSumi.conf              global default');
    Lines.Add('#   ~/.config/vkSumi/games/<exe>.conf         per-game overrides (auto-created)');
    Lines.Add('#');
    Lines.Add('# Per-game files merge on top of the global one, only set what you wanna change.');
    Lines.Add('# Save and the layer reloads via inotify, no game restart needed.');
    Lines.Add('#');
    Lines.Add('# 0 = no change for every knob.');
    Lines.Add('# + = more / brighter.');
    Lines.Add('# - = less / darker.');
    Lines.Add('');
    Lines.Add('PER_GAME_CONFIG_CREATION = false');
    Lines.Add('');
    
    Lines.Add('enabled     = ' + LowerCase(BoolToStr(Settings.Enabled, True)));
    if Settings.ToggleKeys <> '' then
      Lines.Add('toggle_keys = ' + Settings.ToggleKeys + '    # in-game hotkey, X11 + XWayland (Wine/Proton)')
    else
      Lines.Add('toggle_keys = Shift_R+F9    # in-game hotkey, X11 + XWayland (Wine/Proton)');
    Lines.Add('');
    
    Lines.Add('# tone');
    for i := 0 to 3 do
    begin
      if i = 2 then // exposure — -3..3
        Val := (Settings.TrackbarPositions[i] - 300) / 100
      else
        Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# color');
    for i := 4 to 8 do
    begin
      if i = 6 then // hue_deg — -180..180
        Val := Settings.TrackbarPositions[i] - 180
      else
        Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# per-channel gain');
    for i := 9 to 11 do
    begin
      Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# log-grading');
    for i := 12 to 14 do
    begin
      Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;

    if not DirectoryExists(ExtractFileDir(Settings.SumiCfgFile)) then
      ForceDirectories(ExtractFileDir(Settings.SumiCfgFile));
    if FileExists(Settings.SumiCfgFile) then
      DeleteFile(Settings.SumiCfgFile);
    Lines.SaveToFile(Settings.SumiCfgFile);

    // Update bgmod.conf with ENABLE_VKSUMI setting
    if Settings.ActiveGameName <> '' then
      FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
    else
      FGModFilePath := GetFGModPath + PathDelim + 'bgmod.conf';

    ForceDirectories(ExtractFilePath(FGModFilePath));
    Ini := TIniFile.Create(FGModFilePath);
    try
      if Settings.Enabled then
      begin
        Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '1');
        Ini.WriteString('Config', 'ENABLE_VKSUMI', '1');
      end
      else
      begin
        Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '0');
        Ini.WriteString('Config', 'ENABLE_VKSUMI', '0');
      end;
    finally
      Ini.Free;
    end;

    Result := True;
  finally
    Lines.Free;
  end;
end;

function SaveOptiScalerConfigCore(const Settings: TOptiScalerSettings; const EnvGamemodeRun, LaunchCommandSuffix: string; GeneralCheckbox1Checked, ActiveGameIsNonSteam, ActiveGameIsNonSteamLocal: Boolean; out ErrMsg: string; out LaunchCommand: string): Boolean;
var
  SelectedDllName, DllNameWithoutExt: string;
  OptiScalerIniPath: string;
  OptiCfg: TConfigFile;
  SelectedShortcutKey, ScaleValue: string;
  ScaleFloat: Double;
  FS: TFormatSettings;
  OverrideNvapiDllValue: string;
  DxgiValue: string;
  LoadAsiPluginsValue: string;
  Fsr4UpdateValue: string;
  FakeNvapiIniPath: string;
  FakeCfg: TConfigFile;
  ForceReflexValue: string;
  ForceLatencyFlexValue, LatencyFlexModeValue: string;
  EnableTraceLogsValue: string;
  FGModPath, FGModDestPath, VarsFilePath: string;
  Lines: TStringList;
  i: Integer;
  Ini: TIniFile;
  FGModFilePath: string;
begin
  Result := False;
  ErrMsg := '';
  LaunchCommand := '';

  // Get the bgmod.conf path
  if Settings.ActiveGameName <> '' then
    FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
  else
    FGModFilePath := GetOptiScalerInstallPath + PathDelim + 'bgmod.conf';

  // Get selected DLL name from index
  case Settings.FilenameItemIndex of
    0: SelectedDllName := OPTI_DLL_DXGI;
    1: SelectedDllName := OPTI_DLL_VERSION;
    2: SelectedDllName := OPTI_DLL_DBGHELP;
    3: SelectedDllName := OPTI_DLL_D3D12;
    4: SelectedDllName := OPTI_DLL_WININET;
    5: SelectedDllName := OPTI_DLL_WINHTTP;
    6: SelectedDllName := OPTI_DLL_WINMM;
    7: SelectedDllName := OPTI_DLL_ASI;
  else
    SelectedDllName := OPTI_DLL_DXGI;
  end;

  DllNameWithoutExt := ChangeFileExt(SelectedDllName, '');

  ForceDirectories(ExtractFilePath(FGModFilePath));
  Ini := TIniFile.Create(FGModFilePath);
  try
    Ini.WriteString('Config', 'GOVERLAY_OPTISCALER', '1');
    Ini.WriteString('Config', 'DLL', SelectedDllName);
    Ini.WriteString('Config', 'PRESERVE_INI', 'true');

    if Settings.EmuFp8Checked then
      Ini.WriteString('Env', 'DXIL_SPIRV_CONFIG', 'wmma_rdna3_workaround')
    else
      Ini.DeleteKey('Env', 'DXIL_SPIRV_CONFIG');
  finally
    Ini.Free;
  end;

  // Get OptiScaler.ini file path
  if Settings.ActiveGameName <> '' then
    OptiScalerIniPath := GetGameConfigDir(Settings.ActiveGameName) + 'OptiScaler.ini'
  else
    OptiScalerIniPath := GetOptiScalerInstallPath + PathDelim + 'OptiScaler.ini';

  SelectedShortcutKey := Trim(Settings.ShortcutKey);
  if SelectedShortcutKey = '' then
    SelectedShortcutKey := 'auto';

  // Calculate Scale value (divide by 10)
  ScaleFloat := Settings.MenuScalePosition / 10.0;
  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';
  ScaleValue := FloatToStrF(ScaleFloat, ffFixed, 3, 1, FS);

  if Settings.OverrideChecked then
    OverrideNvapiDllValue := 'true'
  else
    OverrideNvapiDllValue := 'auto';

  if Settings.SpoofChecked then
    DxgiValue := 'auto'
  else
    DxgiValue := 'false';

  if Settings.FsrversionItemIndex = 0 then
    Fsr4UpdateValue := 'True'
  else
    Fsr4UpdateValue := 'auto';

  if Settings.OptipatcherChecked then
    LoadAsiPluginsValue := 'true'
  else
    LoadAsiPluginsValue := 'auto';

  // Update OptiScaler.ini using TConfigFile wrapper
  OptiCfg := TConfigFile.Create;
  try
    if OptiCfg.Load(OptiScalerIniPath) then
    begin
      OptiCfg.SetValue(OPTI_KEY_SHORTCUT, SelectedShortcutKey, OPTI_INI_SECTION_MENU);
      OptiCfg.SetValue(OPTI_KEY_SCALE, ScaleValue, OPTI_INI_SECTION_MENU);
      OptiCfg.SetValue(OPTI_KEY_OVERRIDE_NVAPI, OverrideNvapiDllValue);
      OptiCfg.SetValue(OPTI_KEY_DXGI, DxgiValue);
      OptiCfg.SetValue(OPTI_KEY_LOAD_ASI, LoadAsiPluginsValue);
      OptiCfg.SetValue(OPTI_KEY_FSR4_UPDATE, Fsr4UpdateValue);
      OptiCfg.Save;
    end;
  finally
    OptiCfg.Free;
  end;

  // ##### Now modify fakenvapi.ini file #####
  begin
    if Settings.ActiveGameName <> '' then
      FakeNvapiIniPath := GetGameConfigDir(Settings.ActiveGameName) + 'fakenvapi.ini'
    else
      FakeNvapiIniPath := GetOptiScalerInstallPath + PathDelim + 'fakenvapi.ini';

    if Settings.ForceReflexChecked then
    begin
      case Settings.ReflexItemIndex of
        0: ForceReflexValue := '0';
        1: ForceReflexValue := '1';
        2: ForceReflexValue := '2';
      end;
    end
    else
      ForceReflexValue := '0';

    if Settings.ForceLatencyFlexChecked then
    begin
      ForceLatencyFlexValue := '1';
      case Settings.LatencyFlexItemIndex of
        0: LatencyFlexModeValue := '0';
        1: LatencyFlexModeValue := '1';
        2: LatencyFlexModeValue := '2';
      else
        LatencyFlexModeValue := '0';
      end;
    end
    else
    begin
      ForceLatencyFlexValue := '0';
      LatencyFlexModeValue := '0';
    end;

    if Settings.TraceLogChecked then
      EnableTraceLogsValue := '1'
    else
      EnableTraceLogsValue := '0';

    FakeCfg := TConfigFile.Create;
    try
      if FakeCfg.Load(FakeNvapiIniPath) then
      begin
        FakeCfg.SetValue(FAKE_KEY_FORCE_REFLEX, ForceReflexValue);
        FakeCfg.SetValue(FAKE_KEY_FORCE_LATENCY, ForceLatencyFlexValue);
        FakeCfg.SetValue(FAKE_KEY_LATENCY_MODE, LatencyFlexModeValue);
        FakeCfg.SetValue(FAKE_KEY_TRACE_LOGS, EnableTraceLogsValue);
        
        if (not Settings.ForceReflexChecked or FakeCfg.HasKey(FAKE_KEY_FORCE_REFLEX)) and
           (not Settings.ForceLatencyFlexChecked or (FakeCfg.HasKey(FAKE_KEY_FORCE_LATENCY) and FakeCfg.HasKey(FAKE_KEY_LATENCY_MODE))) then
          FakeCfg.Save
        else
        begin
          if Settings.ForceReflexChecked and not FakeCfg.HasKey(FAKE_KEY_FORCE_REFLEX) then
            ErrMsg := ErrMsg + 'Warning: Could not find force_reflex line in fakenvapi.ini file' + LineEnding;
          if Settings.ForceLatencyFlexChecked and not FakeCfg.HasKey(FAKE_KEY_FORCE_LATENCY) then
            ErrMsg := ErrMsg + 'Warning: Could not find force_latencyflex line in fakenvapi.ini file' + LineEnding;
          if Settings.ForceLatencyFlexChecked and not FakeCfg.HasKey(FAKE_KEY_LATENCY_MODE) then
            ErrMsg := ErrMsg + 'Warning: Could not find latencyflex_mode line in fakenvapi.ini file' + LineEnding;
        end;
      end;
    finally
      FakeCfg.Free;
    end;
  end;

  // ##### Copy FSR4 DLL based on fsrversion selection #####
  try
    FGModPath := GetOptiScalerInstallPath;
    if Settings.ActiveGameName <> '' then
      FGModDestPath := ExcludeTrailingPathDelimiter(GetGameConfigDir(Settings.ActiveGameName))
    else
      FGModDestPath := FGModPath;

    case Settings.FsrversionItemIndex of
      0: // Latest (FP8)
        begin
          if FileExists(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_LATEST' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll') then
          begin
            CopyFile(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_LATEST' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll',
                     IncludeTrailingPathDelimiter(FGModDestPath) + 'amd_fidelityfx_upscaler_dx12.dll');

            VarsFilePath := IncludeTrailingPathDelimiter(FGModDestPath) + 'goverlay.vars';
            if FileExists(VarsFilePath) then
            begin
              Lines := TStringList.Create;
              try
                Lines.LoadFromFile(VarsFilePath);
                for i := Lines.Count - 1 downto 0 do
                  if Pos('fsrversion=', Lines[i]) > 0 then
                    Lines.Delete(i);
                Lines.Add('fsrversion=Latest (FP8)');
                Lines.SaveToFile(VarsFilePath);
              finally
                Lines.Free;
              end;
            end;
          end;
        end;

      1: // 4.0.2c (INT8)
        begin
          if FileExists(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_INT8' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll') then
          begin
            CopyFile(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_INT8' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll',
                     IncludeTrailingPathDelimiter(FGModDestPath) + 'amd_fidelityfx_upscaler_dx12.dll');

            VarsFilePath := IncludeTrailingPathDelimiter(FGModDestPath) + 'goverlay.vars';
            if FileExists(VarsFilePath) then
            begin
              Lines := TStringList.Create;
              try
                Lines.LoadFromFile(VarsFilePath);
                for i := Lines.Count - 1 downto 0 do
                  if Pos('fsrversion=', Lines[i]) > 0 then
                    Lines.Delete(i);
                Lines.Add('fsrversion=4.0.2c (INT8)');
                Lines.SaveToFile(VarsFilePath);
              finally
                Lines.Free;
              end;
            end;
          end;
        end;
    end;
  except
    on E: Exception do
      ErrMsg := ErrMsg + 'Warning: Could not copy FSR4 DLL: ' + E.Message + LineEnding;
  end;

  // Build launch command
  if Settings.ActiveGameName <> '' then
  begin
    if ActiveGameIsNonSteam then
      LaunchCommand := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod '
    else
      LaunchCommand := '"' + GetGameConfigDir(Settings.ActiveGameName) + 'bgmod" ';
  end
  else
    LaunchCommand := '"' + GetFGModPath + '/bgmod" ';

  if GeneralCheckbox1Checked then
    LaunchCommand := LaunchCommand + EnvGamemodeRun + ' ';

  if not ( (Settings.ActiveGameName <> '') and ActiveGameIsNonSteamLocal ) then
    LaunchCommand := LaunchCommand + LaunchCommandSuffix;

  Result := True;
end;

end.
