unit overlay_config;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, IniFiles, FileUtil, StrUtils, Types, configfile, configmanager, configkeys, bgmod_resources, optiscaler_update;

type
  TVkBasaltSettings = record
    BasaltFolder: string;
    BasaltCfgFile: string;
    Version: string;
    Channel: string;
    ToggleKey: string;
    CasPosition: Integer;
    FxaaPosition: Integer;
    SmaaPosition: Integer;
    DlsPosition: Integer;
    ReshadeEffects: TStrings;
    ActiveGameName: string;
  end;

  TVkSumiSettings = record
    SumiFolder: string;
    SumiCfgFile: string;
    Version: string;
    Channel: string;
    Enabled: Boolean;
    ToggleKeys: string;
    TrackbarPositions: array[0..14] of Integer;
    ActiveGameName: string;
  end;

  TOptiScalerSettings = record
    ActiveGameName: string;
    Version: string;
    Channel: string;
    FilenameItemIndex: Integer;
    EmuFp8Checked: Boolean;
    ShortcutKey: string;
    MenuScalePosition: Integer;
    OverrideChecked: Boolean;
    SpoofChecked: Boolean;
    FsrversionItemIndex: Integer;
    OptipatcherChecked: Boolean;
    
    // FakeNvapi options
    ForceReflexChecked: Boolean;
    ReflexItemIndex: Integer;
    ForceLatencyFlexChecked: Boolean;
    LatencyFlexItemIndex: Integer;
    TraceLogChecked: Boolean;
  end;

function SanitizeFileName(const AName: string): string;
function GetGameConfigDir(const AGameName: string): string;

function SaveVkBasaltConfig(const Settings: TVkBasaltSettings; out ErrMsg: string): Boolean;
function SaveVkSumiConfig(const Settings: TVkSumiSettings; out ErrMsg: string): Boolean;
function SaveOptiScalerConfigCore(const Settings: TOptiScalerSettings; const EnvGamemodeRun, LaunchCommandSuffix: string; GeneralCheckbox1Checked, ActiveGameIsNonSteam, ActiveGameIsNonSteamLocal: Boolean; out ErrMsg: string; out LaunchCommand: string): Boolean;

function LoadVkBasaltConfig(const CfgFile: string; const AvEffectsList, ActEffectsList: TStrings; out Settings: TVkBasaltSettings): Boolean;
function LoadVkSumiConfig(const CfgFile: string; out Settings: TVkSumiSettings): Boolean;
function LoadOptiScalerConfig(const ActiveGameName: string; out Settings: TOptiScalerSettings): Boolean;

implementation

function SanitizeFileName(const AName: string): string;
var
  i: Integer;
begin
  Result := AName;
  for i := 1 to Length(Result) do
    if Result[i] in ['/', '\', ':', '*', '?', '"', '<', '>', '|', ''''] then
      Result[i] := '_';
end;

function GetGameConfigDir(const AGameName: string): string;
begin
  Result := IncludeTrailingPathDelimiter(TConfigManager.GetHostDataDir) +
            'goverlay/gameconfig/' + SanitizeFileName(AGameName) + '/';
end;

function SaveVkBasaltConfig(const Settings: TVkBasaltSettings; out ErrMsg: string): Boolean;
var
  RepoDir, RelPath, EffectName, EffectKey, FullPath, EffectsLine: string;
  TexPath, IncPath: string;
  Lines: TStringList;
  Sharp: Double;
  FxaaQuality: Double;
  SmaaCorner: Double;
  DlsSharp: Double;
  FS: TFormatSettings;
  i: Integer;
  Ini: TIniFile;
  FGModFilePath: string;
begin
  Result := False;
  ErrMsg := '';

  if Settings.BasaltFolder = '' then
  begin
    ErrMsg := 'vkBasalt directory not found';
    Exit;
  end;

  RepoDir := IncludeTrailingPathDelimiter(Settings.BasaltFolder) + 'reshade-shaders';
  Lines := TStringList.Create;
  try
    Lines.Add('################### File Generated by Goverlay ' + Settings.Version + ' ' + Settings.Channel + ' ###################');
    Lines.Add('toggleKey = ' + Settings.ToggleKey);
    Lines.Add('enableOnLaunch = True');
    Lines.Add('');
    
    // --- create effects list" ---
    EffectsLine := '';
    // 1) CAS (if active)
    if Settings.CasPosition >= 1 then
      EffectsLine := EffectsLine + 'cas';
    // 2) FXAA (if active)
    if Settings.FxaaPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'fxaa';
    end;
    // 3) SMAA (if active)
    if Settings.SmaaPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'smaa';
    end;
    // 4) DLS (if active)
    if Settings.DlsPosition >= 1 then
    begin
      if EffectsLine <> '' then
        EffectsLine := EffectsLine + ':';
      EffectsLine := EffectsLine + 'dls';
    end;
    // 5) reshade effects on the list
    if Assigned(Settings.ReshadeEffects) then
    begin
      for i := 0 to Settings.ReshadeEffects.Count - 1 do
      begin
        RelPath := Settings.ReshadeEffects[i];
        EffectName := ChangeFileExt(ExtractFileName(RelPath), '');
        if EffectsLine <> '' then
          EffectsLine := EffectsLine + ':';
        EffectsLine := EffectsLine + EffectName;
      end;
    end;
    if EffectsLine <> '' then
      Lines.Add('effects = ' + EffectsLine);
    Lines.Add('');
    
    // --- CAS adjustment if active ---
    if Settings.CasPosition >= 1 then
    begin
      Sharp := Settings.CasPosition / 10.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('casSharpness = ' + FloatToStrF(Sharp, ffFixed, 3, 1, FS));
    end;
    // --- FXAA adjustment if active ---
    if Settings.FxaaPosition >= 1 then
    begin
      FxaaQuality := Settings.FxaaPosition / 10.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('fxaaQualitySubpix = ' + FloatToStrF(FxaaQuality, ffFixed, 3, 1, FS));
    end;
    // --- SMAA adjustment if active ---
    if Settings.SmaaPosition >= 1 then
    begin
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      SmaaCorner := 25.0 * (Settings.SmaaPosition - 1) / 9.0;
      Lines.Add('smaaCornerRounding = ' + FloatToStrF(SmaaCorner, ffFixed, 3, 1, FS));
      Lines.Add('smaaThreshold = ' + FloatToStrF(0.1 - 0.05 * (Settings.SmaaPosition - 1) / 9.0, ffFixed, 3, 2, FS));
      Lines.Add('smaaMaxSearchSteps = ' + IntToStr(Round(16 + 16 * (Settings.SmaaPosition - 1) / 9.0)));
      Lines.Add('smaaMaxSearchStepsDiag = ' + IntToStr(Round(8 + 8 * (Settings.SmaaPosition - 1) / 9.0)));
    end;
    // --- DLS adjustment if active ---
    if Settings.DlsPosition >= 1 then
    begin
      DlsSharp := (Settings.DlsPosition - 1) / 9.0;
      FS := DefaultFormatSettings;
      FS.DecimalSeparator := '.';
      Lines.Add('dlsSharpness = ' + FloatToStrF(DlsSharp, ffFixed, 3, 1, FS));
    end;
    // --- Map reshade effects ---
    if Assigned(Settings.ReshadeEffects) then
    begin
      for i := 0 to Settings.ReshadeEffects.Count - 1 do
      begin
        RelPath := Settings.ReshadeEffects[i];
        EffectName := ChangeFileExt(ExtractFileName(RelPath), '');
        EffectKey := EffectName;
        FullPath := IncludeTrailingPathDelimiter(RepoDir) + RelPath;
        Lines.Add(EffectKey + ' = ' + FullPath);
      end;
    end;
    Lines.Add('');
    TexPath := IncludeTrailingPathDelimiter(RepoDir) + 'Textures';
    IncPath := IncludeTrailingPathDelimiter(RepoDir) + 'Shaders';
    Lines.Add('reshadeTexturePath = ' + TexPath);
    Lines.Add('reshadeIncludePath = ' + IncPath);
    
    // --- Save ---
    if not DirectoryExists(ExtractFileDir(Settings.BasaltCfgFile)) then
      ForceDirectories(ExtractFileDir(Settings.BasaltCfgFile));
    if FileExists(Settings.BasaltCfgFile) then
      DeleteFile(Settings.BasaltCfgFile);
    Lines.SaveToFile(Settings.BasaltCfgFile);

    // Update bgmod.conf with GOVERLAY_VKBASALT=1
    if Settings.ActiveGameName <> '' then
      FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
    else
      FGModFilePath := GetFGModPath + PathDelim + 'bgmod.conf';

    ForceDirectories(ExtractFilePath(FGModFilePath));
    Ini := TIniFile.Create(FGModFilePath);
    try
      Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '1');
    finally
      Ini.Free;
    end;

    Result := True;
  finally
    Lines.Free;
  end;
end;

function SaveVkSumiConfig(const Settings: TVkSumiSettings; out ErrMsg: string): Boolean;
const
  KEYS: array[0..14] of string = (
    'brightness', 'contrast', 'exposure', 'gamma',
    'saturation', 'vibrance', 'hue_deg', 'temperature', 'tint',
    'red_gain', 'green_gain', 'blue_gain',
    'shadows', 'midtones', 'highlights'
  );
var
  Lines: TStringList;
  FS: TFormatSettings;
  Val: Double;
  i: Integer;
  FGModFilePath: string;
  Ini: TIniFile;
begin
  Result := False;
  ErrMsg := '';
  
  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';

  Lines := TStringList.Create;
  try
    Lines.Add('################### File Generated by Goverlay ' + Settings.Version + ' ' + Settings.Channel + ' ###################');
    Lines.Add('# vkSumi color grading');
    Lines.Add('#');
    Lines.Add('# Lives at:');
    Lines.Add('#   ~/.config/vkSumi/vkSumi.conf              global default');
    Lines.Add('#   ~/.config/vkSumi/games/<exe>.conf         per-game overrides (auto-created)');
    Lines.Add('#');
    Lines.Add('# Per-game files merge on top of the global one, only set what you wanna change.');
    Lines.Add('# Save and the layer reloads via inotify, no game restart needed.');
    Lines.Add('#');
    Lines.Add('# 0 = no change for every knob.');
    Lines.Add('# + = more / brighter.');
    Lines.Add('# - = less / darker.');
    Lines.Add('');
    Lines.Add('PER_GAME_CONFIG_CREATION = false');
    Lines.Add('');
    
    Lines.Add('enabled     = ' + LowerCase(BoolToStr(Settings.Enabled, True)));
    if Settings.ToggleKeys <> '' then
      Lines.Add('toggle_keys = ' + Settings.ToggleKeys + '    # in-game hotkey, X11 + XWayland (Wine/Proton)')
    else
      Lines.Add('toggle_keys = Shift_R+F9    # in-game hotkey, X11 + XWayland (Wine/Proton)');
    Lines.Add('');
    
    Lines.Add('# tone');
    for i := 0 to 3 do
    begin
      if i = 2 then // exposure — -3..3
        Val := (Settings.TrackbarPositions[i] - 300) / 100
      else
        Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# color');
    for i := 4 to 8 do
    begin
      if i = 6 then // hue_deg — -180..180
        Val := Settings.TrackbarPositions[i] - 180
      else
        Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# per-channel gain');
    for i := 9 to 11 do
    begin
      Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;
    Lines.Add('');
    
    Lines.Add('# log-grading');
    for i := 12 to 14 do
    begin
      Val := (Settings.TrackbarPositions[i] - 100) / 100;
      Lines.Add(KEYS[i] + ' = ' + FormatFloat('0.0', Val, FS));
    end;

    if not DirectoryExists(ExtractFileDir(Settings.SumiCfgFile)) then
      ForceDirectories(ExtractFileDir(Settings.SumiCfgFile));
    if FileExists(Settings.SumiCfgFile) then
      DeleteFile(Settings.SumiCfgFile);
    Lines.SaveToFile(Settings.SumiCfgFile);

    // Update bgmod.conf with ENABLE_VKSUMI setting
    if Settings.ActiveGameName <> '' then
      FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
    else
      FGModFilePath := GetFGModPath + PathDelim + 'bgmod.conf';

    ForceDirectories(ExtractFilePath(FGModFilePath));
    Ini := TIniFile.Create(FGModFilePath);
    try
      if Settings.Enabled then
      begin
        Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '1');
        Ini.WriteString('Config', 'ENABLE_VKSUMI', '1');
      end
      else
      begin
        Ini.WriteString('Config', 'GOVERLAY_VKBASALT', '0');
        Ini.WriteString('Config', 'ENABLE_VKSUMI', '0');
      end;
    finally
      Ini.Free;
    end;

    Result := True;
  finally
    Lines.Free;
  end;
end;

function SaveOptiScalerConfigCore(const Settings: TOptiScalerSettings; const EnvGamemodeRun, LaunchCommandSuffix: string; GeneralCheckbox1Checked, ActiveGameIsNonSteam, ActiveGameIsNonSteamLocal: Boolean; out ErrMsg: string; out LaunchCommand: string): Boolean;
var
  SelectedDllName, DllNameWithoutExt: string;
  OptiScalerIniPath: string;
  OptiCfg: TConfigFile;
  SelectedShortcutKey, ScaleValue: string;
  ScaleFloat: Double;
  FS: TFormatSettings;
  OverrideNvapiDllValue: string;
  DxgiValue: string;
  LoadAsiPluginsValue: string;
  Fsr4UpdateValue: string;
  FakeNvapiIniPath: string;
  FakeCfg: TConfigFile;
  ForceReflexValue: string;
  ForceLatencyFlexValue, LatencyFlexModeValue: string;
  EnableTraceLogsValue: string;
  FGModPath, FGModDestPath, VarsFilePath: string;
  Lines: TStringList;
  i: Integer;
  Ini: TIniFile;
  FGModFilePath: string;
begin
  Result := False;
  ErrMsg := '';
  LaunchCommand := '';

  // Get the bgmod.conf path
  if Settings.ActiveGameName <> '' then
    FGModFilePath := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod.conf'
  else
    FGModFilePath := GetOptiScalerInstallPath + PathDelim + 'bgmod.conf';

  // Get selected DLL name from index
  case Settings.FilenameItemIndex of
    0: SelectedDllName := OPTI_DLL_DXGI;
    1: SelectedDllName := OPTI_DLL_VERSION;
    2: SelectedDllName := OPTI_DLL_DBGHELP;
    3: SelectedDllName := OPTI_DLL_D3D12;
    4: SelectedDllName := OPTI_DLL_WININET;
    5: SelectedDllName := OPTI_DLL_WINHTTP;
    6: SelectedDllName := OPTI_DLL_WINMM;
    7: SelectedDllName := OPTI_DLL_ASI;
  else
    SelectedDllName := OPTI_DLL_DXGI;
  end;

  DllNameWithoutExt := ChangeFileExt(SelectedDllName, '');

  ForceDirectories(ExtractFilePath(FGModFilePath));
  Ini := TIniFile.Create(FGModFilePath);
  try
    Ini.WriteString('Config', 'GOVERLAY_OPTISCALER', '1');
    Ini.WriteString('Config', 'DLL', SelectedDllName);
    Ini.WriteString('Config', 'PRESERVE_INI', 'true');

    if Settings.EmuFp8Checked then
      Ini.WriteString('Env', 'DXIL_SPIRV_CONFIG', 'wmma_rdna3_workaround')
    else
      Ini.DeleteKey('Env', 'DXIL_SPIRV_CONFIG');
  finally
    Ini.Free;
  end;

  // Get OptiScaler.ini file path
  if Settings.ActiveGameName <> '' then
    OptiScalerIniPath := GetGameConfigDir(Settings.ActiveGameName) + 'OptiScaler.ini'
  else
    OptiScalerIniPath := GetOptiScalerInstallPath + PathDelim + 'OptiScaler.ini';

  SelectedShortcutKey := Trim(Settings.ShortcutKey);
  if SelectedShortcutKey = '' then
    SelectedShortcutKey := 'auto';

  // Calculate Scale value (divide by 10)
  ScaleFloat := Settings.MenuScalePosition / 10.0;
  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';
  ScaleValue := FloatToStrF(ScaleFloat, ffFixed, 3, 1, FS);

  if Settings.OverrideChecked then
    OverrideNvapiDllValue := 'true'
  else
    OverrideNvapiDllValue := 'auto';

  if Settings.SpoofChecked then
    DxgiValue := 'auto'
  else
    DxgiValue := 'false';

  if Settings.FsrversionItemIndex = 0 then
    Fsr4UpdateValue := 'True'
  else
    Fsr4UpdateValue := 'auto';

  if Settings.OptipatcherChecked then
    LoadAsiPluginsValue := 'true'
  else
    LoadAsiPluginsValue := 'auto';

  // Update OptiScaler.ini using TConfigFile wrapper
  OptiCfg := TConfigFile.Create;
  try
    if OptiCfg.Load(OptiScalerIniPath) then
    begin
      OptiCfg.SetValue(OPTI_KEY_SHORTCUT, SelectedShortcutKey, OPTI_INI_SECTION_MENU);
      OptiCfg.SetValue(OPTI_KEY_SCALE, ScaleValue, OPTI_INI_SECTION_MENU);
      OptiCfg.SetValue(OPTI_KEY_OVERRIDE_NVAPI, OverrideNvapiDllValue);
      OptiCfg.SetValue(OPTI_KEY_DXGI, DxgiValue);
      OptiCfg.SetValue(OPTI_KEY_LOAD_ASI, LoadAsiPluginsValue);
      OptiCfg.SetValue(OPTI_KEY_FSR4_UPDATE, Fsr4UpdateValue);
      OptiCfg.Save;
    end;
  finally
    OptiCfg.Free;
  end;

  // ##### Now modify fakenvapi.ini file #####
  begin
    if Settings.ActiveGameName <> '' then
      FakeNvapiIniPath := GetGameConfigDir(Settings.ActiveGameName) + 'fakenvapi.ini'
    else
      FakeNvapiIniPath := GetOptiScalerInstallPath + PathDelim + 'fakenvapi.ini';

    if Settings.ForceReflexChecked then
    begin
      case Settings.ReflexItemIndex of
        0: ForceReflexValue := '0';
        1: ForceReflexValue := '1';
        2: ForceReflexValue := '2';
      end;
    end
    else
      ForceReflexValue := '0';

    if Settings.ForceLatencyFlexChecked then
    begin
      ForceLatencyFlexValue := '1';
      case Settings.LatencyFlexItemIndex of
        0: LatencyFlexModeValue := '0';
        1: LatencyFlexModeValue := '1';
        2: LatencyFlexModeValue := '2';
      else
        LatencyFlexModeValue := '0';
      end;
    end
    else
    begin
      ForceLatencyFlexValue := '0';
      LatencyFlexModeValue := '0';
    end;

    if Settings.TraceLogChecked then
      EnableTraceLogsValue := '1'
    else
      EnableTraceLogsValue := '0';

    FakeCfg := TConfigFile.Create;
    try
      if FakeCfg.Load(FakeNvapiIniPath) then
      begin
        FakeCfg.SetValue(FAKE_KEY_FORCE_REFLEX, ForceReflexValue);
        FakeCfg.SetValue(FAKE_KEY_FORCE_LATENCY, ForceLatencyFlexValue);
        FakeCfg.SetValue(FAKE_KEY_LATENCY_MODE, LatencyFlexModeValue);
        FakeCfg.SetValue(FAKE_KEY_TRACE_LOGS, EnableTraceLogsValue);
        
        if (not Settings.ForceReflexChecked or FakeCfg.HasKey(FAKE_KEY_FORCE_REFLEX)) and
           (not Settings.ForceLatencyFlexChecked or (FakeCfg.HasKey(FAKE_KEY_FORCE_LATENCY) and FakeCfg.HasKey(FAKE_KEY_LATENCY_MODE))) then
          FakeCfg.Save
        else
        begin
          if Settings.ForceReflexChecked and not FakeCfg.HasKey(FAKE_KEY_FORCE_REFLEX) then
            ErrMsg := ErrMsg + 'Warning: Could not find force_reflex line in fakenvapi.ini file' + LineEnding;
          if Settings.ForceLatencyFlexChecked and not FakeCfg.HasKey(FAKE_KEY_FORCE_LATENCY) then
            ErrMsg := ErrMsg + 'Warning: Could not find force_latencyflex line in fakenvapi.ini file' + LineEnding;
          if Settings.ForceLatencyFlexChecked and not FakeCfg.HasKey(FAKE_KEY_LATENCY_MODE) then
            ErrMsg := ErrMsg + 'Warning: Could not find latencyflex_mode line in fakenvapi.ini file' + LineEnding;
        end;
      end;
    finally
      FakeCfg.Free;
    end;
  end;

  // ##### Copy FSR4 DLL based on fsrversion selection #####
  try
    FGModPath := GetOptiScalerInstallPath;
    if Settings.ActiveGameName <> '' then
      FGModDestPath := ExcludeTrailingPathDelimiter(GetGameConfigDir(Settings.ActiveGameName))
    else
      FGModDestPath := FGModPath;

    case Settings.FsrversionItemIndex of
      0: // Latest (FP8)
        begin
          if FileExists(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_LATEST' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll') then
          begin
            CopyFile(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_LATEST' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll',
                     IncludeTrailingPathDelimiter(FGModDestPath) + 'amd_fidelityfx_upscaler_dx12.dll');

            VarsFilePath := IncludeTrailingPathDelimiter(FGModDestPath) + 'goverlay.vars';
            if FileExists(VarsFilePath) then
            begin
              Lines := TStringList.Create;
              try
                Lines.LoadFromFile(VarsFilePath);
                for i := Lines.Count - 1 downto 0 do
                  if Pos('fsrversion=', Lines[i]) > 0 then
                    Lines.Delete(i);
                Lines.Add('fsrversion=Latest (FP8)');
                Lines.SaveToFile(VarsFilePath);
              finally
                Lines.Free;
              end;
            end;
          end;
        end;

      1: // 4.0.2c (INT8)
        begin
          if FileExists(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_INT8' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll') then
          begin
            CopyFile(IncludeTrailingPathDelimiter(FGModPath) + 'FSR4_INT8' + PathDelim + 'amd_fidelityfx_upscaler_dx12.dll',
                     IncludeTrailingPathDelimiter(FGModDestPath) + 'amd_fidelityfx_upscaler_dx12.dll');

            VarsFilePath := IncludeTrailingPathDelimiter(FGModDestPath) + 'goverlay.vars';
            if FileExists(VarsFilePath) then
            begin
              Lines := TStringList.Create;
              try
                Lines.LoadFromFile(VarsFilePath);
                for i := Lines.Count - 1 downto 0 do
                  if Pos('fsrversion=', Lines[i]) > 0 then
                    Lines.Delete(i);
                Lines.Add('fsrversion=4.0.2c (INT8)');
                Lines.SaveToFile(VarsFilePath);
              finally
                Lines.Free;
              end;
            end;
          end;
        end;
    end;
  except
    on E: Exception do
      ErrMsg := ErrMsg + 'Warning: Could not copy FSR4 DLL: ' + E.Message + LineEnding;
  end;

  // Build launch command
  if Settings.ActiveGameName <> '' then
  begin
    if ActiveGameIsNonSteam then
      LaunchCommand := GetGameConfigDir(Settings.ActiveGameName) + 'bgmod '
    else
      LaunchCommand := '"' + GetGameConfigDir(Settings.ActiveGameName) + 'bgmod" ';
  end
  else
    LaunchCommand := '"' + GetFGModPath + '/bgmod" ';

  if GeneralCheckbox1Checked then
    LaunchCommand := LaunchCommand + EnvGamemodeRun + ' ';

  if not ( (Settings.ActiveGameName <> '') and ActiveGameIsNonSteamLocal ) then
    LaunchCommand := LaunchCommand + LaunchCommandSuffix;

  Result := True;
end;

function LoadVkBasaltConfig(const CfgFile: string; const AvEffectsList, ActEffectsList: TStrings; out Settings: TVkBasaltSettings): Boolean;
var
  Value, EffectsStr, FullEffectPath: string;
  EffectsList: TStringArray;
  j, k: Integer;
  FloatValue: Double;
  FS: TFormatSettings;
  Cfg: TConfigFile;
begin
  Result := False;
  FillChar(Settings, SizeOf(Settings), 0);
  
  if not FileExists(CfgFile) then
    Exit;

  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';

  Cfg := TConfigFile.Create;
  try
    if not Cfg.Load(CfgFile) then Exit;

    Settings.BasaltCfgFile := CfgFile;
    ActEffectsList.Clear;

    EffectsStr := Cfg.GetValue('effects =', '');
    if EffectsStr <> '' then
    begin
      EffectsList := SplitString(EffectsStr, ':');
      for j := Low(EffectsList) to High(EffectsList) do
      begin
        EffectsList[j] := Trim(EffectsList[j]);
        if SameText(EffectsList[j], 'cas') then
        begin
          if Settings.CasPosition = 0 then
            Settings.CasPosition := 5;
        end
        else if SameText(EffectsList[j], 'fxaa') then
        begin
          if Settings.FxaaPosition = 0 then
            Settings.FxaaPosition := 5;
        end
        else if SameText(EffectsList[j], 'smaa') then
        begin
          if Settings.SmaaPosition = 0 then
            Settings.SmaaPosition := 5;
        end
        else if SameText(EffectsList[j], 'dls') then
        begin
          if Settings.DlsPosition = 0 then
            Settings.DlsPosition := 5;
        end
        else if EffectsList[j] <> '' then
        begin
          FullEffectPath := '';
          for k := 0 to AvEffectsList.Count - 1 do
          begin
            if SameText(ChangeFileExt(ExtractFileName(AvEffectsList[k]), ''), EffectsList[j]) then
            begin
              FullEffectPath := AvEffectsList[k];
              Break;
            end;
          end;
          if FullEffectPath = '' then
            FullEffectPath := EffectsList[j];
          if ActEffectsList.IndexOf(FullEffectPath) = -1 then
            ActEffectsList.Add(FullEffectPath);
        end;
      end;
    end;

    Value := Cfg.GetValue('casSharpness =', '');
    if TryStrToFloat(Value, FloatValue, FS) then
      Settings.CasPosition := Round(FloatValue * 10);

    Value := Cfg.GetValue('fxaaQualitySubpix =', '');
    if TryStrToFloat(Value, FloatValue, FS) then
      Settings.FxaaPosition := Round(FloatValue * 10);

    Value := Cfg.GetValue('smaaCornerRounding =', '');
    if TryStrToFloat(Value, FloatValue, FS) then
      Settings.SmaaPosition := Round(FloatValue / 25 * 9) + 1;

    Value := Cfg.GetValue('dlsSharpness =', '');
    if TryStrToFloat(Value, FloatValue, FS) then
      Settings.DlsPosition := Round(FloatValue * 9) + 1;

    Value := Cfg.GetValue('toggleKey =', '');
    if Value <> '' then
      Settings.ToggleKey := Value;

    Result := True;
  finally
    Cfg.Free;
  end;
end;

function LoadVkSumiConfig(const CfgFile: string; out Settings: TVkSumiSettings): Boolean;
const
  KEYS: array[0..14] of string = (
    'brightness', 'contrast', 'exposure', 'gamma',
    'saturation', 'vibrance', 'hue_deg', 'temperature', 'tint',
    'red_gain', 'green_gain', 'blue_gain',
    'shadows', 'midtones', 'highlights'
  );
  DEFAULTS: array[0..14] of Integer = (
    100, 100, 300, 100,
    100, 100, 180, 100, 100,
    100, 100, 100,
    100, 100, 100
  );
var
  Cfg: TConfigFile;
  i: Integer;
  FS: TFormatSettings;
  ValStr: string;
  Val: Double;
  PosVal: Integer;
begin
  Result := False;
  FillChar(Settings, SizeOf(Settings), 0);
  Settings.SumiCfgFile := CfgFile;
  
  // Set default values first
  Settings.Enabled := True;
  Settings.ToggleKeys := 'Shift_R+F9';
  for i := 0 to 14 do
    Settings.TrackbarPositions[i] := DEFAULTS[i];

  if not FileExists(CfgFile) then
  begin
    Result := True;
    Exit;
  end;

  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';

  Cfg := TConfigFile.Create;
  try
    if Cfg.Load(CfgFile) then
    begin
      Settings.Enabled := Cfg.GetBool('enabled =', True);
      
      ValStr := Cfg.GetValue('toggle_keys =', 'Shift_R+F9');
      i := Pos('#', ValStr);
      if i > 0 then ValStr := Copy(ValStr, 1, i - 1);
      i := Pos(';', ValStr);
      if i > 0 then ValStr := Copy(ValStr, 1, i - 1);
      Settings.ToggleKeys := Trim(ValStr);

      for i := 0 to 14 do
      begin
        ValStr := Cfg.GetValue(KEYS[i] + ' =', '');
        if ValStr <> '' then
        begin
          if TryStrToFloat(ValStr, Val, FS) then
          begin
            if i = 2 then
              PosVal := Round(Val * 100) + 300
            else if i = 6 then
              PosVal := Round(Val) + 180
            else
              PosVal := Round(Val * 100) + 100;

            // Clamp to Min/Max
            if i = 2 then // Exposure: 0..600
            begin
              if PosVal < 0 then PosVal := 0;
              if PosVal > 600 then PosVal := 600;
            end
            else if i = 6 then // Hue: 0..360
            begin
              if PosVal < 0 then PosVal := 0;
              if PosVal > 360 then PosVal := 360;
            end
            else // Others: 0..200
            begin
              if PosVal < 0 then PosVal := 0;
              if PosVal > 200 then PosVal := 200;
            end;

            Settings.TrackbarPositions[i] := PosVal;
          end;
        end;
      end;
      Result := True;
    end;
  finally
    Cfg.Free;
  end;
end;

function LoadOptiScalerConfig(const ActiveGameName: string; out Settings: TOptiScalerSettings): Boolean;
var
  OptiCfg, FakeCfg: TConfigFile;
  OptiScalerIniPath, FakeNvapiIniPath, ConfigPath, VarsPath: string;
  Value, DllName, FsrVer, TrimmedLine, Key, ValStr: string;
  FloatValue: Double;
  FS: TFormatSettings;
  Ini: TIniFile;
  i, SepPos: Integer;
  ConfigLines: TStringList;
begin
  Result := False;
  FillChar(Settings, SizeOf(Settings), 0);
  Settings.ActiveGameName := ActiveGameName;

  // Defaults
  Settings.FilenameItemIndex := 0;
  Settings.EmuFp8Checked := False;
  Settings.ShortcutKey := '0x2d';
  Settings.MenuScalePosition := 10;
  Settings.OverrideChecked := False;
  Settings.SpoofChecked := False;
  Settings.FsrversionItemIndex := 0;
  Settings.OptipatcherChecked := False;
  Settings.ForceReflexChecked := False;
  Settings.ReflexItemIndex := 0;
  Settings.ForceLatencyFlexChecked := False;
  Settings.LatencyFlexItemIndex := 0;
  Settings.TraceLogChecked := False;

  FS := DefaultFormatSettings;
  FS.DecimalSeparator := '.';

  // 1. Load OptiScaler.ini
  if ActiveGameName <> '' then
    OptiScalerIniPath := GetGameConfigDir(ActiveGameName) + 'OptiScaler.ini'
  else
    OptiScalerIniPath := GetOptiScalerInstallPath + PathDelim + 'OptiScaler.ini';

  if FileExists(OptiScalerIniPath) then
  begin
    OptiCfg := TConfigFile.Create;
    try
      if OptiCfg.Load(OptiScalerIniPath) then
      begin
        Value := OptiCfg.GetValue(OPTI_KEY_SHORTCUT, '', OPTI_INI_SECTION_MENU);
        if SameText(Value, 'auto') or (Value = '') then
          Settings.ShortcutKey := '0x2d'
        else
          Settings.ShortcutKey := Value;

        Value := OptiCfg.GetValue(OPTI_KEY_SCALE, '', OPTI_INI_SECTION_MENU);
        if TryStrToFloat(Value, FloatValue, FS) then
          Settings.MenuScalePosition := Round(FloatValue * 10);

        Settings.OverrideChecked := SameText(OptiCfg.GetValue(OPTI_KEY_OVERRIDE_NVAPI, ''), 'true');
        Settings.OptipatcherChecked := SameText(OptiCfg.GetValue(OPTI_KEY_LOAD_ASI, ''), 'true');

        if SameText(OptiCfg.GetValue(OPTI_KEY_FSR4_UPDATE, ''), 'true') then
          Settings.FsrversionItemIndex := 0;

        Settings.SpoofChecked := SameText(OptiCfg.GetValue(OPTI_KEY_DXGI, ''), 'auto');
      end;
    finally
      OptiCfg.Free;
    end;
  end;

  // 2. Load fakenvapi.ini
  if ActiveGameName <> '' then
    FakeNvapiIniPath := GetGameConfigDir(ActiveGameName) + 'fakenvapi.ini'
  else
    FakeNvapiIniPath := GetOptiScalerInstallPath + PathDelim + 'fakenvapi.ini';

  if FileExists(FakeNvapiIniPath) then
  begin
    FakeCfg := TConfigFile.Create;
    try
      if FakeCfg.Load(FakeNvapiIniPath) then
      begin
        Value := FakeCfg.GetValue(FAKE_KEY_FORCE_REFLEX, '0');
        if Value = '0' then
        begin
          Settings.ForceReflexChecked := False;
          Settings.ReflexItemIndex := 0;
        end
        else
        begin
          Settings.ForceReflexChecked := True;
          case Value of
            '1': Settings.ReflexItemIndex := 1;
            '2': Settings.ReflexItemIndex := 2;
          else
            Settings.ReflexItemIndex := 0;
          end;
        end;

        Settings.ForceLatencyFlexChecked := (FakeCfg.GetValue(FAKE_KEY_FORCE_LATENCY, '0') = '1');
        if Settings.ForceLatencyFlexChecked then
        begin
          case FakeCfg.GetValue(FAKE_KEY_LATENCY_MODE, '0') of
            '0': Settings.LatencyFlexItemIndex := 0;
            '1': Settings.LatencyFlexItemIndex := 1;
            '2': Settings.LatencyFlexItemIndex := 2;
          else
            Settings.LatencyFlexItemIndex := 0;
          end;
        end;

        Settings.TraceLogChecked := (FakeCfg.GetValue(FAKE_KEY_TRACE_LOGS, '0') = '1');
      end;
    finally
      FakeCfg.Free;
    end;
  end;

  // 3. Load bgmod.conf and goverlay.vars
  if ActiveGameName <> '' then
    ConfigPath := GetGameConfigDir(ActiveGameName) + 'bgmod.conf'
  else
    ConfigPath := GetOptiScalerInstallPath + PathDelim + 'bgmod.conf';

  if not FileExists(ConfigPath) then
  begin
    Settings.FilenameItemIndex := 0;
    Settings.EmuFp8Checked := False;
  end
  else
  begin
    Ini := TIniFile.Create(ConfigPath);
    try
      DllName := Ini.ReadString('Config', 'DLL', 'dxgi.dll');
      if SameText(DllName, 'dxgi.dll') then
        Settings.FilenameItemIndex := 0
      else if SameText(DllName, 'version.dll') then
        Settings.FilenameItemIndex := 1
      else if SameText(DllName, 'dbghelp.dll') then
        Settings.FilenameItemIndex := 2
      else if SameText(DllName, 'd3d12.dll') then
        Settings.FilenameItemIndex := 3
      else if SameText(DllName, 'wininet.dll') then
        Settings.FilenameItemIndex := 4
      else if SameText(DllName, 'winhttp.dll') then
        Settings.FilenameItemIndex := 5
      else if SameText(DllName, 'winmm.dll') then
        Settings.FilenameItemIndex := 6
      else if SameText(DllName, 'OptiScaler.asi') then
        Settings.FilenameItemIndex := 7
      else
        Settings.FilenameItemIndex := 0;

      Settings.EmuFp8Checked := Ini.ReadString('Env', 'DXIL_SPIRV_CONFIG', '') <> '';
    finally
      Ini.Free;
    end;
  end;

  if ActiveGameName <> '' then
    VarsPath := IncludeTrailingPathDelimiter(GetGameConfigDir(ActiveGameName)) + 'goverlay.vars'
  else
    VarsPath := IncludeTrailingPathDelimiter(GetOptiScalerInstallPath) + 'goverlay.vars';

  if FileExists(VarsPath) then
  begin
    ConfigLines := TStringList.Create;
    try
      ConfigLines.LoadFromFile(VarsPath);
      FsrVer := '';
      for i := 0 to ConfigLines.Count - 1 do
      begin
        TrimmedLine := Trim(ConfigLines[i]);
        SepPos := Pos('=', TrimmedLine);
        if SepPos > 0 then
        begin
          Key   := Copy(TrimmedLine, 1, SepPos - 1);
          Value := Copy(TrimmedLine, SepPos + 1, Length(TrimmedLine));
          if SameText(Key, 'fsrversion') then
          begin
            FsrVer := Value;
            Break;
          end;
        end;
      end;
      if FsrVer = '4.0.2c (INT8)' then
        Settings.FsrversionItemIndex := 1
      else
        Settings.FsrversionItemIndex := 0;
    finally
      ConfigLines.Free;
    end;
  end;

  Result := True;
end;

end.
