#ifndef PLANET_TEXTURES_GLSL
#define PLANET_TEXTURES_GLSL

#define PLANET_TEXTURE_HEIGHTMAP 0
#define PLANET_TEXTURE_NORMALMAP 1
#define PLANET_TEXTURE_BLENDMAP 2
#define PLANET_TEXTURE_GRASSMAP 3
#define PLANET_TEXTURE_WATERMAP 4
#define PLANET_TEXTURE_BRUSHES 5
#define PLANET_TEXTURE_PRECIPITATIONMAP 6
#define PLANET_TEXTURE_ATMOSPHEREMAP 7
#define PLANET_TEXTURE_RAINTEXTURE 8
#define PLANET_TEXTURE_RAINNORMALTEXTURE 9
#define PLANET_TEXTURE_RAINSTREAKSNORMALTEXTURE 10

#endif 