#ifndef SOLID_PRIMITIVE_GLSL
#define SOLID_PRIMITIVE_GLSL

#define PRIMITIVE_TOPOLOGY_POINT 0u
#define PRIMITIVE_TOPOLOGY_POINT_WIREFRAME 1u
#define PRIMITIVE_TOPOLOGY_LINE 2u
#define PRIMITIVE_TOPOLOGY_TRIANGLE 3u
#define PRIMITIVE_TOPOLOGY_TRIANGLE_WIREFRAME 4u
#define PRIMITIVE_TOPOLOGY_QUAD 5u
#define PRIMITIVE_TOPOLOGY_QUAD_WIREFRAME 6u

#endif
