#!/usr/bin/env bash
set -euo pipefail
glslangValidator -V cube.vert -o cube_vert.spv
glslangValidator -V cube.frag -o cube_frag.spv
for f in *.spv; do
  # spirv-opt --strip-debug --unify-const --flatten-decorations --eliminate-dead-const "$f" -o "$f"
  spirv-opt --strip-debug --unify-const --flatten-decorations --eliminate-dead-const --strength-reduction --simplify-instructions --remove-duplicates -O "$f" -o "$f"
done
cp -f cube_vert.spv ../../../../assets/shaders/cube/cube_vert.spv
cp -f cube_frag.spv ../../../../assets/shaders/cube/cube_frag.spv
rm -f *.spv