name: Bug Report
description: Report a bug or unexpected behavior in GOverlay
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install GOverlay?
      options:
        - Flatpak (Flathub)
        - Native (pacman/zypper/eopkg)
        - AUR (goverlay-git)
        - AppImage
        - Tarball
        - Built from source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: GOverlay Version
      description: What version of GOverlay are you using?
      placeholder: "e.g., 1.7.0"
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: Which Linux distribution are you using?
      placeholder: "e.g., Arch Linux, Ubuntu 24.04, Fedora 40"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this bug?
      multiple: true
      options:
        - MangoHud
        - vkBasalt
        - OptiScaler
        - FGMOD
        - UI/Interface
        - Configuration Loading/Saving
        - Theme System
        - Other
    validations:
      required: true

  - type: input
    id: mangohud-version
    attributes:
      label: MangoHud Version (if applicable)
      placeholder: "e.g., 0.7.2"

  - type: input
    id: vkbasalt-version
    attributes:
      label: vkBasalt Version (if applicable)
      placeholder: "e.g., 0.3.2"

  - type: input
    id: optiscaler-version
    attributes:
      label: OptiScaler Version (if applicable)
      placeholder: "e.g., 0.7.9-2"

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Include any relevant logs, error messages, or screenshots
      placeholder: Paste logs here or attach screenshots
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I am using the latest version of GOverlay
          required: false
