#!/bin/sh
# gen_spirv.sh — Compile GLSL compute shaders to SPIR-V and embed as C header
#
# Requires glslc (from Vulkan SDK) at build time.
# Generates shader_spirv.h with uint32_t arrays for each shader.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders"
OUTPUT="$SCRIPT_DIR/shader_spirv.h"

GLSLC="${GLSLC:-glslc}"

# Check for glslc
if ! command -v "$GLSLC" >/dev/null 2>&1; then
    echo "ERROR: glslc not found. Install the Vulkan SDK or set GLSLC envvar." >&2
    exit 1
fi

SHADERS="
conv_forward
conv_backward_data
conv_backward_filter
conv_backward_bias
pixel_shuffle
pixel_unshuffle
relu_backward
adam_update
loss_grad
loss_reduce
scale_buffer
"

echo "Compiling compute shaders..."

cat > "$OUTPUT" <<'EOF'
/*
 * shader_spirv.h — Auto-generated SPIR-V bytecode for CNN compute shaders
 *
 * DO NOT EDIT — generated by gen_spirv.sh
 */

#ifndef SHADER_SPIRV_H
#define SHADER_SPIRV_H

#include <stdint.h>

EOF

for shader in $SHADERS; do
    SRC="$SHADER_DIR/${shader}.comp"
    SPV="$SHADER_DIR/${shader}.spv"

    if [ ! -f "$SRC" ]; then
        echo "  WARNING: $SRC not found, skipping" >&2
        continue
    fi

    echo "  $shader.comp → $shader.spv"
    "$GLSLC" --target-env=vulkan1.0 -O "$SRC" -o "$SPV"

    # Convert SPIR-V binary to C uint32_t array
    NAME=$(echo "$shader" | tr 'a-z' 'A-Z')
    VARNAME="spirv_${shader}"

    SIZE=$(wc -c < "$SPV")
    WORDS=$((SIZE / 4))

    printf "/* %s.comp — %d bytes, %d words */\n" "$shader" "$SIZE" "$WORDS" >> "$OUTPUT"
    printf "static const uint32_t %s[] = {\n" "$VARNAME" >> "$OUTPUT"

    # Use hexdump to dump as uint32 (little-endian, one per line)
    hexdump -v -e '1/4 "    0x%08x,\n"' "$SPV" >> "$OUTPUT"

    printf "};\n" >> "$OUTPUT"
    printf "#define %s_SIZE %d\n\n" "$NAME" "$SIZE" >> "$OUTPUT"

    rm -f "$SPV"
done

cat >> "$OUTPUT" <<'EOF'
#endif /* SHADER_SPIRV_H */
EOF

echo "Generated $OUTPUT"
