.TH goverlay 1 "" "" ""
.SH NAME
goverlay \- Graphical UI to help manage Vulkan/OpenGL overlays
.SH SYNOPSIS
\fBgoverlay [--style STYLE]\fR
.SH DESCRIPTION
\fBGOverlay\fR can configure Vulkan / OpenGL overlays with a preview. Currently supported are MangoHud, vkBasalt and ReplaySorcery.
.SH OPTIONS
.TP 8
.B --style STYLE
Force a specific Qt style. An alternative to this option is setting the QT_STYLE_OVERRIDE environment variable.
.SH NOTE
It is recommended to use the Breeze (Qt/KDE) or Adwaita (Gtk/Gnome) theme.
