#!/usr/bin/env bash
set -euo pipefail
glslangValidator -V triangle.vert -o triangle_vert.spv
glslangValidator -V triangle.frag -o triangle_frag.spv
for f in *.spv; do
  # spirv-opt --strip-debug --unify-const --flatten-decorations --eliminate-dead-const "$f" -o "$f"
  spirv-opt --strip-debug --unify-const --flatten-decorations --eliminate-dead-const --strength-reduction --simplify-instructions --remove-duplicates -O "$f" -o "$f"
done
cp -f triangle_vert.spv ../../../../assets/shaders/triangle/triangle_vert.spv
cp -f triangle_frag.spv ../../../../assets/shaders/triangle/triangle_frag.spv
rm -f *.spv