private
function GetAA:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAB:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetABA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAG:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAR:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetARA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBA:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBB:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBG:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBR:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGA:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGB:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGG:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGR:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPP:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPS:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPST:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPT:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQP:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQS:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQST:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQT:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRA:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRB:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRG:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRR:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRA:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRB:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRG:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRR:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRA:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRB:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRG:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRR:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSP:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSS:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSST:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetST:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTP:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTS:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTST:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTT:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTP:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTS:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTST:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTT:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTP:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTQ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTS:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTT:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWW:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWX:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWY:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXW:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXX:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXY:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYW:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYX:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYY:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZW:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZX:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZY:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZ:TpvVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZW:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZX:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZY:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZ:TpvVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZW:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZX:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZY:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZZ:TpvVector4; {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAB(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABGR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABRG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAG(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGBR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGRB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAR(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARBG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARGB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBA(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAGR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBARG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBG(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGAR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGRA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBR(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRAG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRGA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGA(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGAB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGABR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGAR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGARB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGB(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBAR(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBR(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBRA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGR(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRAB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRBA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQST(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQT(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQTS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPS(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSQT(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPST(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSTQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPT(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTQS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTSQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQP(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPST(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPT(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPTS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQS(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSPT(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQST(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSTP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQT(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTPS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTSP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRA(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRABG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAGB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRB(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBAG(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBG(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBGA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRG(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGA(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGAB(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGB(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGBA(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSP(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPQT(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPT(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPTQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQPT(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQT(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQTP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetST(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTPQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTQP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTP(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPQS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPSQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQPS(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQS(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQSP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTS(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSP(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSPQ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSQ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSQP(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWX(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXYZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXZY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWY(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYXZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYZX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZXY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZYX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXW(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWYZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWZY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXY(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYWZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYZW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZWY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZYW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYW(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWXZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWZX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYX(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXWZ(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXZ(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXZW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZ(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZWX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZXW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZW(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWXY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWYX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZX(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXWY(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXY(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXYW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZY(const pValue:TpvVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYW(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYWX(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYX(const pValue:TpvVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYXW(const pValue:TpvVector4); {$ifdef CAN_INLINE}inline;{$endif}
public
property aa:TpvVector2 read GetAA;
property aaa:TpvVector3 read GetAAA;
property aaaa:TpvVector4 read GetAAAA;
property aaab:TpvVector4 read GetAAAB;
property aaag:TpvVector4 read GetAAAG;
property aaar:TpvVector4 read GetAAAR;
property aab:TpvVector3 read GetAAB;
property aaba:TpvVector4 read GetAABA;
property aabb:TpvVector4 read GetAABB;
property aabg:TpvVector4 read GetAABG;
property aabr:TpvVector4 read GetAABR;
property aag:TpvVector3 read GetAAG;
property aaga:TpvVector4 read GetAAGA;
property aagb:TpvVector4 read GetAAGB;
property aagg:TpvVector4 read GetAAGG;
property aagr:TpvVector4 read GetAAGR;
property aar:TpvVector3 read GetAAR;
property aara:TpvVector4 read GetAARA;
property aarb:TpvVector4 read GetAARB;
property aarg:TpvVector4 read GetAARG;
property aarr:TpvVector4 read GetAARR;
property ab:TpvVector2 read GetAB write SetAB;
property aba:TpvVector3 read GetABA;
property abaa:TpvVector4 read GetABAA;
property abab:TpvVector4 read GetABAB;
property abag:TpvVector4 read GetABAG;
property abar:TpvVector4 read GetABAR;
property abb:TpvVector3 read GetABB;
property abba:TpvVector4 read GetABBA;
property abbb:TpvVector4 read GetABBB;
property abbg:TpvVector4 read GetABBG;
property abbr:TpvVector4 read GetABBR;
property abg:TpvVector3 read GetABG write SetABG;
property abga:TpvVector4 read GetABGA;
property abgb:TpvVector4 read GetABGB;
property abgg:TpvVector4 read GetABGG;
property abgr:TpvVector4 read GetABGR write SetABGR;
property abr:TpvVector3 read GetABR write SetABR;
property abra:TpvVector4 read GetABRA;
property abrb:TpvVector4 read GetABRB;
property abrg:TpvVector4 read GetABRG write SetABRG;
property abrr:TpvVector4 read GetABRR;
property ag:TpvVector2 read GetAG write SetAG;
property aga:TpvVector3 read GetAGA;
property agaa:TpvVector4 read GetAGAA;
property agab:TpvVector4 read GetAGAB;
property agag:TpvVector4 read GetAGAG;
property agar:TpvVector4 read GetAGAR;
property agb:TpvVector3 read GetAGB write SetAGB;
property agba:TpvVector4 read GetAGBA;
property agbb:TpvVector4 read GetAGBB;
property agbg:TpvVector4 read GetAGBG;
property agbr:TpvVector4 read GetAGBR write SetAGBR;
property agg:TpvVector3 read GetAGG;
property agga:TpvVector4 read GetAGGA;
property aggb:TpvVector4 read GetAGGB;
property aggg:TpvVector4 read GetAGGG;
property aggr:TpvVector4 read GetAGGR;
property agr:TpvVector3 read GetAGR write SetAGR;
property agra:TpvVector4 read GetAGRA;
property agrb:TpvVector4 read GetAGRB write SetAGRB;
property agrg:TpvVector4 read GetAGRG;
property agrr:TpvVector4 read GetAGRR;
property ar:TpvVector2 read GetAR write SetAR;
property ara:TpvVector3 read GetARA;
property araa:TpvVector4 read GetARAA;
property arab:TpvVector4 read GetARAB;
property arag:TpvVector4 read GetARAG;
property arar:TpvVector4 read GetARAR;
property arb:TpvVector3 read GetARB write SetARB;
property arba:TpvVector4 read GetARBA;
property arbb:TpvVector4 read GetARBB;
property arbg:TpvVector4 read GetARBG write SetARBG;
property arbr:TpvVector4 read GetARBR;
property arg:TpvVector3 read GetARG write SetARG;
property arga:TpvVector4 read GetARGA;
property argb:TpvVector4 read GetARGB write SetARGB;
property argg:TpvVector4 read GetARGG;
property argr:TpvVector4 read GetARGR;
property arr:TpvVector3 read GetARR;
property arra:TpvVector4 read GetARRA;
property arrb:TpvVector4 read GetARRB;
property arrg:TpvVector4 read GetARRG;
property arrr:TpvVector4 read GetARRR;
property ba:TpvVector2 read GetBA write SetBA;
property baa:TpvVector3 read GetBAA;
property baaa:TpvVector4 read GetBAAA;
property baab:TpvVector4 read GetBAAB;
property baag:TpvVector4 read GetBAAG;
property baar:TpvVector4 read GetBAAR;
property bab:TpvVector3 read GetBAB;
property baba:TpvVector4 read GetBABA;
property babb:TpvVector4 read GetBABB;
property babg:TpvVector4 read GetBABG;
property babr:TpvVector4 read GetBABR;
property bag:TpvVector3 read GetBAG write SetBAG;
property baga:TpvVector4 read GetBAGA;
property bagb:TpvVector4 read GetBAGB;
property bagg:TpvVector4 read GetBAGG;
property bagr:TpvVector4 read GetBAGR write SetBAGR;
property bar:TpvVector3 read GetBAR write SetBAR;
property bara:TpvVector4 read GetBARA;
property barb:TpvVector4 read GetBARB;
property barg:TpvVector4 read GetBARG write SetBARG;
property barr:TpvVector4 read GetBARR;
property bb:TpvVector2 read GetBB;
property bba:TpvVector3 read GetBBA;
property bbaa:TpvVector4 read GetBBAA;
property bbab:TpvVector4 read GetBBAB;
property bbag:TpvVector4 read GetBBAG;
property bbar:TpvVector4 read GetBBAR;
property bbb:TpvVector3 read GetBBB;
property bbba:TpvVector4 read GetBBBA;
property bbbb:TpvVector4 read GetBBBB;
property bbbg:TpvVector4 read GetBBBG;
property bbbr:TpvVector4 read GetBBBR;
property bbg:TpvVector3 read GetBBG;
property bbga:TpvVector4 read GetBBGA;
property bbgb:TpvVector4 read GetBBGB;
property bbgg:TpvVector4 read GetBBGG;
property bbgr:TpvVector4 read GetBBGR;
property bbr:TpvVector3 read GetBBR;
property bbra:TpvVector4 read GetBBRA;
property bbrb:TpvVector4 read GetBBRB;
property bbrg:TpvVector4 read GetBBRG;
property bbrr:TpvVector4 read GetBBRR;
property bg:TpvVector2 read GetBG write SetBG;
property bga:TpvVector3 read GetBGA write SetBGA;
property bgaa:TpvVector4 read GetBGAA;
property bgab:TpvVector4 read GetBGAB;
property bgag:TpvVector4 read GetBGAG;
property bgar:TpvVector4 read GetBGAR write SetBGAR;
property bgb:TpvVector3 read GetBGB;
property bgba:TpvVector4 read GetBGBA;
property bgbb:TpvVector4 read GetBGBB;
property bgbg:TpvVector4 read GetBGBG;
property bgbr:TpvVector4 read GetBGBR;
property bgg:TpvVector3 read GetBGG;
property bgga:TpvVector4 read GetBGGA;
property bggb:TpvVector4 read GetBGGB;
property bggg:TpvVector4 read GetBGGG;
property bggr:TpvVector4 read GetBGGR;
property bgr:TpvVector3 read GetBGR write SetBGR;
property bgra:TpvVector4 read GetBGRA write SetBGRA;
property bgrb:TpvVector4 read GetBGRB;
property bgrg:TpvVector4 read GetBGRG;
property bgrr:TpvVector4 read GetBGRR;
property br:TpvVector2 read GetBR write SetBR;
property bra:TpvVector3 read GetBRA write SetBRA;
property braa:TpvVector4 read GetBRAA;
property brab:TpvVector4 read GetBRAB;
property brag:TpvVector4 read GetBRAG write SetBRAG;
property brar:TpvVector4 read GetBRAR;
property brb:TpvVector3 read GetBRB;
property brba:TpvVector4 read GetBRBA;
property brbb:TpvVector4 read GetBRBB;
property brbg:TpvVector4 read GetBRBG;
property brbr:TpvVector4 read GetBRBR;
property brg:TpvVector3 read GetBRG write SetBRG;
property brga:TpvVector4 read GetBRGA write SetBRGA;
property brgb:TpvVector4 read GetBRGB;
property brgg:TpvVector4 read GetBRGG;
property brgr:TpvVector4 read GetBRGR;
property brr:TpvVector3 read GetBRR;
property brra:TpvVector4 read GetBRRA;
property brrb:TpvVector4 read GetBRRB;
property brrg:TpvVector4 read GetBRRG;
property brrr:TpvVector4 read GetBRRR;
property ga:TpvVector2 read GetGA write SetGA;
property gaa:TpvVector3 read GetGAA;
property gaaa:TpvVector4 read GetGAAA;
property gaab:TpvVector4 read GetGAAB;
property gaag:TpvVector4 read GetGAAG;
property gaar:TpvVector4 read GetGAAR;
property gab:TpvVector3 read GetGAB write SetGAB;
property gaba:TpvVector4 read GetGABA;
property gabb:TpvVector4 read GetGABB;
property gabg:TpvVector4 read GetGABG;
property gabr:TpvVector4 read GetGABR write SetGABR;
property gag:TpvVector3 read GetGAG;
property gaga:TpvVector4 read GetGAGA;
property gagb:TpvVector4 read GetGAGB;
property gagg:TpvVector4 read GetGAGG;
property gagr:TpvVector4 read GetGAGR;
property gar:TpvVector3 read GetGAR write SetGAR;
property gara:TpvVector4 read GetGARA;
property garb:TpvVector4 read GetGARB write SetGARB;
property garg:TpvVector4 read GetGARG;
property garr:TpvVector4 read GetGARR;
property gb:TpvVector2 read GetGB write SetGB;
property gba:TpvVector3 read GetGBA write SetGBA;
property gbaa:TpvVector4 read GetGBAA;
property gbab:TpvVector4 read GetGBAB;
property gbag:TpvVector4 read GetGBAG;
property gbar:TpvVector4 read GetGBAR write SetGBAR;
property gbb:TpvVector3 read GetGBB;
property gbba:TpvVector4 read GetGBBA;
property gbbb:TpvVector4 read GetGBBB;
property gbbg:TpvVector4 read GetGBBG;
property gbbr:TpvVector4 read GetGBBR;
property gbg:TpvVector3 read GetGBG;
property gbga:TpvVector4 read GetGBGA;
property gbgb:TpvVector4 read GetGBGB;
property gbgg:TpvVector4 read GetGBGG;
property gbgr:TpvVector4 read GetGBGR;
property gbr:TpvVector3 read GetGBR write SetGBR;
property gbra:TpvVector4 read GetGBRA write SetGBRA;
property gbrb:TpvVector4 read GetGBRB;
property gbrg:TpvVector4 read GetGBRG;
property gbrr:TpvVector4 read GetGBRR;
property gg:TpvVector2 read GetGG;
property gga:TpvVector3 read GetGGA;
property ggaa:TpvVector4 read GetGGAA;
property ggab:TpvVector4 read GetGGAB;
property ggag:TpvVector4 read GetGGAG;
property ggar:TpvVector4 read GetGGAR;
property ggb:TpvVector3 read GetGGB;
property ggba:TpvVector4 read GetGGBA;
property ggbb:TpvVector4 read GetGGBB;
property ggbg:TpvVector4 read GetGGBG;
property ggbr:TpvVector4 read GetGGBR;
property ggg:TpvVector3 read GetGGG;
property ggga:TpvVector4 read GetGGGA;
property gggb:TpvVector4 read GetGGGB;
property gggg:TpvVector4 read GetGGGG;
property gggr:TpvVector4 read GetGGGR;
property ggr:TpvVector3 read GetGGR;
property ggra:TpvVector4 read GetGGRA;
property ggrb:TpvVector4 read GetGGRB;
property ggrg:TpvVector4 read GetGGRG;
property ggrr:TpvVector4 read GetGGRR;
property gr:TpvVector2 read GetGR write SetGR;
property gra:TpvVector3 read GetGRA write SetGRA;
property graa:TpvVector4 read GetGRAA;
property grab:TpvVector4 read GetGRAB write SetGRAB;
property grag:TpvVector4 read GetGRAG;
property grar:TpvVector4 read GetGRAR;
property grb:TpvVector3 read GetGRB write SetGRB;
property grba:TpvVector4 read GetGRBA write SetGRBA;
property grbb:TpvVector4 read GetGRBB;
property grbg:TpvVector4 read GetGRBG;
property grbr:TpvVector4 read GetGRBR;
property grg:TpvVector3 read GetGRG;
property grga:TpvVector4 read GetGRGA;
property grgb:TpvVector4 read GetGRGB;
property grgg:TpvVector4 read GetGRGG;
property grgr:TpvVector4 read GetGRGR;
property grr:TpvVector3 read GetGRR;
property grra:TpvVector4 read GetGRRA;
property grrb:TpvVector4 read GetGRRB;
property grrg:TpvVector4 read GetGRRG;
property grrr:TpvVector4 read GetGRRR;
property pp:TpvVector2 read GetPP;
property ppp:TpvVector3 read GetPPP;
property pppp:TpvVector4 read GetPPPP;
property pppq:TpvVector4 read GetPPPQ;
property ppps:TpvVector4 read GetPPPS;
property pppt:TpvVector4 read GetPPPT;
property ppq:TpvVector3 read GetPPQ;
property ppqp:TpvVector4 read GetPPQP;
property ppqq:TpvVector4 read GetPPQQ;
property ppqs:TpvVector4 read GetPPQS;
property ppqt:TpvVector4 read GetPPQT;
property pps:TpvVector3 read GetPPS;
property ppsp:TpvVector4 read GetPPSP;
property ppsq:TpvVector4 read GetPPSQ;
property ppss:TpvVector4 read GetPPSS;
property ppst:TpvVector4 read GetPPST;
property ppt:TpvVector3 read GetPPT;
property pptp:TpvVector4 read GetPPTP;
property pptq:TpvVector4 read GetPPTQ;
property ppts:TpvVector4 read GetPPTS;
property pptt:TpvVector4 read GetPPTT;
property pq:TpvVector2 read GetPQ write SetPQ;
property pqp:TpvVector3 read GetPQP;
property pqpp:TpvVector4 read GetPQPP;
property pqpq:TpvVector4 read GetPQPQ;
property pqps:TpvVector4 read GetPQPS;
property pqpt:TpvVector4 read GetPQPT;
property pqq:TpvVector3 read GetPQQ;
property pqqp:TpvVector4 read GetPQQP;
property pqqq:TpvVector4 read GetPQQQ;
property pqqs:TpvVector4 read GetPQQS;
property pqqt:TpvVector4 read GetPQQT;
property pqs:TpvVector3 read GetPQS write SetPQS;
property pqsp:TpvVector4 read GetPQSP;
property pqsq:TpvVector4 read GetPQSQ;
property pqss:TpvVector4 read GetPQSS;
property pqst:TpvVector4 read GetPQST write SetPQST;
property pqt:TpvVector3 read GetPQT write SetPQT;
property pqtp:TpvVector4 read GetPQTP;
property pqtq:TpvVector4 read GetPQTQ;
property pqts:TpvVector4 read GetPQTS write SetPQTS;
property pqtt:TpvVector4 read GetPQTT;
property ps:TpvVector2 read GetPS write SetPS;
property psp:TpvVector3 read GetPSP;
property pspp:TpvVector4 read GetPSPP;
property pspq:TpvVector4 read GetPSPQ;
property psps:TpvVector4 read GetPSPS;
property pspt:TpvVector4 read GetPSPT;
property psq:TpvVector3 read GetPSQ write SetPSQ;
property psqp:TpvVector4 read GetPSQP;
property psqq:TpvVector4 read GetPSQQ;
property psqs:TpvVector4 read GetPSQS;
property psqt:TpvVector4 read GetPSQT write SetPSQT;
property pss:TpvVector3 read GetPSS;
property pssp:TpvVector4 read GetPSSP;
property pssq:TpvVector4 read GetPSSQ;
property psss:TpvVector4 read GetPSSS;
property psst:TpvVector4 read GetPSST;
property pst:TpvVector3 read GetPST write SetPST;
property pstp:TpvVector4 read GetPSTP;
property pstq:TpvVector4 read GetPSTQ write SetPSTQ;
property psts:TpvVector4 read GetPSTS;
property pstt:TpvVector4 read GetPSTT;
property pt:TpvVector2 read GetPT write SetPT;
property ptp:TpvVector3 read GetPTP;
property ptpp:TpvVector4 read GetPTPP;
property ptpq:TpvVector4 read GetPTPQ;
property ptps:TpvVector4 read GetPTPS;
property ptpt:TpvVector4 read GetPTPT;
property ptq:TpvVector3 read GetPTQ write SetPTQ;
property ptqp:TpvVector4 read GetPTQP;
property ptqq:TpvVector4 read GetPTQQ;
property ptqs:TpvVector4 read GetPTQS write SetPTQS;
property ptqt:TpvVector4 read GetPTQT;
property pts:TpvVector3 read GetPTS write SetPTS;
property ptsp:TpvVector4 read GetPTSP;
property ptsq:TpvVector4 read GetPTSQ write SetPTSQ;
property ptss:TpvVector4 read GetPTSS;
property ptst:TpvVector4 read GetPTST;
property ptt:TpvVector3 read GetPTT;
property pttp:TpvVector4 read GetPTTP;
property pttq:TpvVector4 read GetPTTQ;
property ptts:TpvVector4 read GetPTTS;
property pttt:TpvVector4 read GetPTTT;
property qp:TpvVector2 read GetQP write SetQP;
property qpp:TpvVector3 read GetQPP;
property qppp:TpvVector4 read GetQPPP;
property qppq:TpvVector4 read GetQPPQ;
property qpps:TpvVector4 read GetQPPS;
property qppt:TpvVector4 read GetQPPT;
property qpq:TpvVector3 read GetQPQ;
property qpqp:TpvVector4 read GetQPQP;
property qpqq:TpvVector4 read GetQPQQ;
property qpqs:TpvVector4 read GetQPQS;
property qpqt:TpvVector4 read GetQPQT;
property qps:TpvVector3 read GetQPS write SetQPS;
property qpsp:TpvVector4 read GetQPSP;
property qpsq:TpvVector4 read GetQPSQ;
property qpss:TpvVector4 read GetQPSS;
property qpst:TpvVector4 read GetQPST write SetQPST;
property qpt:TpvVector3 read GetQPT write SetQPT;
property qptp:TpvVector4 read GetQPTP;
property qptq:TpvVector4 read GetQPTQ;
property qpts:TpvVector4 read GetQPTS write SetQPTS;
property qptt:TpvVector4 read GetQPTT;
property qq:TpvVector2 read GetQQ;
property qqp:TpvVector3 read GetQQP;
property qqpp:TpvVector4 read GetQQPP;
property qqpq:TpvVector4 read GetQQPQ;
property qqps:TpvVector4 read GetQQPS;
property qqpt:TpvVector4 read GetQQPT;
property qqq:TpvVector3 read GetQQQ;
property qqqp:TpvVector4 read GetQQQP;
property qqqq:TpvVector4 read GetQQQQ;
property qqqs:TpvVector4 read GetQQQS;
property qqqt:TpvVector4 read GetQQQT;
property qqs:TpvVector3 read GetQQS;
property qqsp:TpvVector4 read GetQQSP;
property qqsq:TpvVector4 read GetQQSQ;
property qqss:TpvVector4 read GetQQSS;
property qqst:TpvVector4 read GetQQST;
property qqt:TpvVector3 read GetQQT;
property qqtp:TpvVector4 read GetQQTP;
property qqtq:TpvVector4 read GetQQTQ;
property qqts:TpvVector4 read GetQQTS;
property qqtt:TpvVector4 read GetQQTT;
property qs:TpvVector2 read GetQS write SetQS;
property qsp:TpvVector3 read GetQSP write SetQSP;
property qspp:TpvVector4 read GetQSPP;
property qspq:TpvVector4 read GetQSPQ;
property qsps:TpvVector4 read GetQSPS;
property qspt:TpvVector4 read GetQSPT write SetQSPT;
property qsq:TpvVector3 read GetQSQ;
property qsqp:TpvVector4 read GetQSQP;
property qsqq:TpvVector4 read GetQSQQ;
property qsqs:TpvVector4 read GetQSQS;
property qsqt:TpvVector4 read GetQSQT;
property qss:TpvVector3 read GetQSS;
property qssp:TpvVector4 read GetQSSP;
property qssq:TpvVector4 read GetQSSQ;
property qsss:TpvVector4 read GetQSSS;
property qsst:TpvVector4 read GetQSST;
property qst:TpvVector3 read GetQST write SetQST;
property qstp:TpvVector4 read GetQSTP write SetQSTP;
property qstq:TpvVector4 read GetQSTQ;
property qsts:TpvVector4 read GetQSTS;
property qstt:TpvVector4 read GetQSTT;
property qt:TpvVector2 read GetQT write SetQT;
property qtp:TpvVector3 read GetQTP write SetQTP;
property qtpp:TpvVector4 read GetQTPP;
property qtpq:TpvVector4 read GetQTPQ;
property qtps:TpvVector4 read GetQTPS write SetQTPS;
property qtpt:TpvVector4 read GetQTPT;
property qtq:TpvVector3 read GetQTQ;
property qtqp:TpvVector4 read GetQTQP;
property qtqq:TpvVector4 read GetQTQQ;
property qtqs:TpvVector4 read GetQTQS;
property qtqt:TpvVector4 read GetQTQT;
property qts:TpvVector3 read GetQTS write SetQTS;
property qtsp:TpvVector4 read GetQTSP write SetQTSP;
property qtsq:TpvVector4 read GetQTSQ;
property qtss:TpvVector4 read GetQTSS;
property qtst:TpvVector4 read GetQTST;
property qtt:TpvVector3 read GetQTT;
property qttp:TpvVector4 read GetQTTP;
property qttq:TpvVector4 read GetQTTQ;
property qtts:TpvVector4 read GetQTTS;
property qttt:TpvVector4 read GetQTTT;
property ra:TpvVector2 read GetRA write SetRA;
property raa:TpvVector3 read GetRAA;
property raaa:TpvVector4 read GetRAAA;
property raab:TpvVector4 read GetRAAB;
property raag:TpvVector4 read GetRAAG;
property raar:TpvVector4 read GetRAAR;
property rab:TpvVector3 read GetRAB write SetRAB;
property raba:TpvVector4 read GetRABA;
property rabb:TpvVector4 read GetRABB;
property rabg:TpvVector4 read GetRABG write SetRABG;
property rabr:TpvVector4 read GetRABR;
property rag:TpvVector3 read GetRAG write SetRAG;
property raga:TpvVector4 read GetRAGA;
property ragb:TpvVector4 read GetRAGB write SetRAGB;
property ragg:TpvVector4 read GetRAGG;
property ragr:TpvVector4 read GetRAGR;
property rar:TpvVector3 read GetRAR;
property rara:TpvVector4 read GetRARA;
property rarb:TpvVector4 read GetRARB;
property rarg:TpvVector4 read GetRARG;
property rarr:TpvVector4 read GetRARR;
property rb:TpvVector2 read GetRB write SetRB;
property rba:TpvVector3 read GetRBA write SetRBA;
property rbaa:TpvVector4 read GetRBAA;
property rbab:TpvVector4 read GetRBAB;
property rbag:TpvVector4 read GetRBAG write SetRBAG;
property rbar:TpvVector4 read GetRBAR;
property rbb:TpvVector3 read GetRBB;
property rbba:TpvVector4 read GetRBBA;
property rbbb:TpvVector4 read GetRBBB;
property rbbg:TpvVector4 read GetRBBG;
property rbbr:TpvVector4 read GetRBBR;
property rbg:TpvVector3 read GetRBG write SetRBG;
property rbga:TpvVector4 read GetRBGA write SetRBGA;
property rbgb:TpvVector4 read GetRBGB;
property rbgg:TpvVector4 read GetRBGG;
property rbgr:TpvVector4 read GetRBGR;
property rbr:TpvVector3 read GetRBR;
property rbra:TpvVector4 read GetRBRA;
property rbrb:TpvVector4 read GetRBRB;
property rbrg:TpvVector4 read GetRBRG;
property rbrr:TpvVector4 read GetRBRR;
property rg:TpvVector2 read GetRG write SetRG;
property rga:TpvVector3 read GetRGA write SetRGA;
property rgaa:TpvVector4 read GetRGAA;
property rgab:TpvVector4 read GetRGAB write SetRGAB;
property rgag:TpvVector4 read GetRGAG;
property rgar:TpvVector4 read GetRGAR;
property rgb:TpvVector3 read GetRGB write SetRGB;
property rgba:TpvVector4 read GetRGBA write SetRGBA;
property rgbb:TpvVector4 read GetRGBB;
property rgbg:TpvVector4 read GetRGBG;
property rgbr:TpvVector4 read GetRGBR;
property rgg:TpvVector3 read GetRGG;
property rgga:TpvVector4 read GetRGGA;
property rggb:TpvVector4 read GetRGGB;
property rggg:TpvVector4 read GetRGGG;
property rggr:TpvVector4 read GetRGGR;
property rgr:TpvVector3 read GetRGR;
property rgra:TpvVector4 read GetRGRA;
property rgrb:TpvVector4 read GetRGRB;
property rgrg:TpvVector4 read GetRGRG;
property rgrr:TpvVector4 read GetRGRR;
property rr:TpvVector2 read GetRR;
property rra:TpvVector3 read GetRRA;
property rraa:TpvVector4 read GetRRAA;
property rrab:TpvVector4 read GetRRAB;
property rrag:TpvVector4 read GetRRAG;
property rrar:TpvVector4 read GetRRAR;
property rrb:TpvVector3 read GetRRB;
property rrba:TpvVector4 read GetRRBA;
property rrbb:TpvVector4 read GetRRBB;
property rrbg:TpvVector4 read GetRRBG;
property rrbr:TpvVector4 read GetRRBR;
property rrg:TpvVector3 read GetRRG;
property rrga:TpvVector4 read GetRRGA;
property rrgb:TpvVector4 read GetRRGB;
property rrgg:TpvVector4 read GetRRGG;
property rrgr:TpvVector4 read GetRRGR;
property rrr:TpvVector3 read GetRRR;
property rrra:TpvVector4 read GetRRRA;
property rrrb:TpvVector4 read GetRRRB;
property rrrg:TpvVector4 read GetRRRG;
property rrrr:TpvVector4 read GetRRRR;
property sp:TpvVector2 read GetSP write SetSP;
property spp:TpvVector3 read GetSPP;
property sppp:TpvVector4 read GetSPPP;
property sppq:TpvVector4 read GetSPPQ;
property spps:TpvVector4 read GetSPPS;
property sppt:TpvVector4 read GetSPPT;
property spq:TpvVector3 read GetSPQ write SetSPQ;
property spqp:TpvVector4 read GetSPQP;
property spqq:TpvVector4 read GetSPQQ;
property spqs:TpvVector4 read GetSPQS;
property spqt:TpvVector4 read GetSPQT write SetSPQT;
property sps:TpvVector3 read GetSPS;
property spsp:TpvVector4 read GetSPSP;
property spsq:TpvVector4 read GetSPSQ;
property spss:TpvVector4 read GetSPSS;
property spst:TpvVector4 read GetSPST;
property spt:TpvVector3 read GetSPT write SetSPT;
property sptp:TpvVector4 read GetSPTP;
property sptq:TpvVector4 read GetSPTQ write SetSPTQ;
property spts:TpvVector4 read GetSPTS;
property sptt:TpvVector4 read GetSPTT;
property sq:TpvVector2 read GetSQ write SetSQ;
property sqp:TpvVector3 read GetSQP write SetSQP;
property sqpp:TpvVector4 read GetSQPP;
property sqpq:TpvVector4 read GetSQPQ;
property sqps:TpvVector4 read GetSQPS;
property sqpt:TpvVector4 read GetSQPT write SetSQPT;
property sqq:TpvVector3 read GetSQQ;
property sqqp:TpvVector4 read GetSQQP;
property sqqq:TpvVector4 read GetSQQQ;
property sqqs:TpvVector4 read GetSQQS;
property sqqt:TpvVector4 read GetSQQT;
property sqs:TpvVector3 read GetSQS;
property sqsp:TpvVector4 read GetSQSP;
property sqsq:TpvVector4 read GetSQSQ;
property sqss:TpvVector4 read GetSQSS;
property sqst:TpvVector4 read GetSQST;
property sqt:TpvVector3 read GetSQT write SetSQT;
property sqtp:TpvVector4 read GetSQTP write SetSQTP;
property sqtq:TpvVector4 read GetSQTQ;
property sqts:TpvVector4 read GetSQTS;
property sqtt:TpvVector4 read GetSQTT;
property ss:TpvVector2 read GetSS;
property ssp:TpvVector3 read GetSSP;
property sspp:TpvVector4 read GetSSPP;
property sspq:TpvVector4 read GetSSPQ;
property ssps:TpvVector4 read GetSSPS;
property sspt:TpvVector4 read GetSSPT;
property ssq:TpvVector3 read GetSSQ;
property ssqp:TpvVector4 read GetSSQP;
property ssqq:TpvVector4 read GetSSQQ;
property ssqs:TpvVector4 read GetSSQS;
property ssqt:TpvVector4 read GetSSQT;
property sss:TpvVector3 read GetSSS;
property sssp:TpvVector4 read GetSSSP;
property sssq:TpvVector4 read GetSSSQ;
property ssss:TpvVector4 read GetSSSS;
property ssst:TpvVector4 read GetSSST;
property sst:TpvVector3 read GetSST;
property sstp:TpvVector4 read GetSSTP;
property sstq:TpvVector4 read GetSSTQ;
property ssts:TpvVector4 read GetSSTS;
property sstt:TpvVector4 read GetSSTT;
property st:TpvVector2 read GetST write SetST;
property stp:TpvVector3 read GetSTP write SetSTP;
property stpp:TpvVector4 read GetSTPP;
property stpq:TpvVector4 read GetSTPQ write SetSTPQ;
property stps:TpvVector4 read GetSTPS;
property stpt:TpvVector4 read GetSTPT;
property stq:TpvVector3 read GetSTQ write SetSTQ;
property stqp:TpvVector4 read GetSTQP write SetSTQP;
property stqq:TpvVector4 read GetSTQQ;
property stqs:TpvVector4 read GetSTQS;
property stqt:TpvVector4 read GetSTQT;
property sts:TpvVector3 read GetSTS;
property stsp:TpvVector4 read GetSTSP;
property stsq:TpvVector4 read GetSTSQ;
property stss:TpvVector4 read GetSTSS;
property stst:TpvVector4 read GetSTST;
property stt:TpvVector3 read GetSTT;
property sttp:TpvVector4 read GetSTTP;
property sttq:TpvVector4 read GetSTTQ;
property stts:TpvVector4 read GetSTTS;
property sttt:TpvVector4 read GetSTTT;
property tp:TpvVector2 read GetTP write SetTP;
property tpp:TpvVector3 read GetTPP;
property tppp:TpvVector4 read GetTPPP;
property tppq:TpvVector4 read GetTPPQ;
property tpps:TpvVector4 read GetTPPS;
property tppt:TpvVector4 read GetTPPT;
property tpq:TpvVector3 read GetTPQ write SetTPQ;
property tpqp:TpvVector4 read GetTPQP;
property tpqq:TpvVector4 read GetTPQQ;
property tpqs:TpvVector4 read GetTPQS write SetTPQS;
property tpqt:TpvVector4 read GetTPQT;
property tps:TpvVector3 read GetTPS write SetTPS;
property tpsp:TpvVector4 read GetTPSP;
property tpsq:TpvVector4 read GetTPSQ write SetTPSQ;
property tpss:TpvVector4 read GetTPSS;
property tpst:TpvVector4 read GetTPST;
property tpt:TpvVector3 read GetTPT;
property tptp:TpvVector4 read GetTPTP;
property tptq:TpvVector4 read GetTPTQ;
property tpts:TpvVector4 read GetTPTS;
property tptt:TpvVector4 read GetTPTT;
property tq:TpvVector2 read GetTQ write SetTQ;
property tqp:TpvVector3 read GetTQP write SetTQP;
property tqpp:TpvVector4 read GetTQPP;
property tqpq:TpvVector4 read GetTQPQ;
property tqps:TpvVector4 read GetTQPS write SetTQPS;
property tqpt:TpvVector4 read GetTQPT;
property tqq:TpvVector3 read GetTQQ;
property tqqp:TpvVector4 read GetTQQP;
property tqqq:TpvVector4 read GetTQQQ;
property tqqs:TpvVector4 read GetTQQS;
property tqqt:TpvVector4 read GetTQQT;
property tqs:TpvVector3 read GetTQS write SetTQS;
property tqsp:TpvVector4 read GetTQSP write SetTQSP;
property tqsq:TpvVector4 read GetTQSQ;
property tqss:TpvVector4 read GetTQSS;
property tqst:TpvVector4 read GetTQST;
property tqt:TpvVector3 read GetTQT;
property tqtp:TpvVector4 read GetTQTP;
property tqtq:TpvVector4 read GetTQTQ;
property tqts:TpvVector4 read GetTQTS;
property tqtt:TpvVector4 read GetTQTT;
property ts:TpvVector2 read GetTS write SetTS;
property tsp:TpvVector3 read GetTSP write SetTSP;
property tspp:TpvVector4 read GetTSPP;
property tspq:TpvVector4 read GetTSPQ write SetTSPQ;
property tsps:TpvVector4 read GetTSPS;
property tspt:TpvVector4 read GetTSPT;
property tsq:TpvVector3 read GetTSQ write SetTSQ;
property tsqp:TpvVector4 read GetTSQP write SetTSQP;
property tsqq:TpvVector4 read GetTSQQ;
property tsqs:TpvVector4 read GetTSQS;
property tsqt:TpvVector4 read GetTSQT;
property tss:TpvVector3 read GetTSS;
property tssp:TpvVector4 read GetTSSP;
property tssq:TpvVector4 read GetTSSQ;
property tsss:TpvVector4 read GetTSSS;
property tsst:TpvVector4 read GetTSST;
property tst:TpvVector3 read GetTST;
property tstp:TpvVector4 read GetTSTP;
property tstq:TpvVector4 read GetTSTQ;
property tsts:TpvVector4 read GetTSTS;
property tstt:TpvVector4 read GetTSTT;
property tt:TpvVector2 read GetTT;
property ttp:TpvVector3 read GetTTP;
property ttpp:TpvVector4 read GetTTPP;
property ttpq:TpvVector4 read GetTTPQ;
property ttps:TpvVector4 read GetTTPS;
property ttpt:TpvVector4 read GetTTPT;
property ttq:TpvVector3 read GetTTQ;
property ttqp:TpvVector4 read GetTTQP;
property ttqq:TpvVector4 read GetTTQQ;
property ttqs:TpvVector4 read GetTTQS;
property ttqt:TpvVector4 read GetTTQT;
property tts:TpvVector3 read GetTTS;
property ttsp:TpvVector4 read GetTTSP;
property ttsq:TpvVector4 read GetTTSQ;
property ttss:TpvVector4 read GetTTSS;
property ttst:TpvVector4 read GetTTST;
property ttt:TpvVector3 read GetTTT;
property tttp:TpvVector4 read GetTTTP;
property tttq:TpvVector4 read GetTTTQ;
property ttts:TpvVector4 read GetTTTS;
property tttt:TpvVector4 read GetTTTT;
property ww:TpvVector2 read GetWW;
property www:TpvVector3 read GetWWW;
property wwww:TpvVector4 read GetWWWW;
property wwwx:TpvVector4 read GetWWWX;
property wwwy:TpvVector4 read GetWWWY;
property wwwz:TpvVector4 read GetWWWZ;
property wwx:TpvVector3 read GetWWX;
property wwxw:TpvVector4 read GetWWXW;
property wwxx:TpvVector4 read GetWWXX;
property wwxy:TpvVector4 read GetWWXY;
property wwxz:TpvVector4 read GetWWXZ;
property wwy:TpvVector3 read GetWWY;
property wwyw:TpvVector4 read GetWWYW;
property wwyx:TpvVector4 read GetWWYX;
property wwyy:TpvVector4 read GetWWYY;
property wwyz:TpvVector4 read GetWWYZ;
property wwz:TpvVector3 read GetWWZ;
property wwzw:TpvVector4 read GetWWZW;
property wwzx:TpvVector4 read GetWWZX;
property wwzy:TpvVector4 read GetWWZY;
property wwzz:TpvVector4 read GetWWZZ;
property wx:TpvVector2 read GetWX write SetWX;
property wxw:TpvVector3 read GetWXW;
property wxww:TpvVector4 read GetWXWW;
property wxwx:TpvVector4 read GetWXWX;
property wxwy:TpvVector4 read GetWXWY;
property wxwz:TpvVector4 read GetWXWZ;
property wxx:TpvVector3 read GetWXX;
property wxxw:TpvVector4 read GetWXXW;
property wxxx:TpvVector4 read GetWXXX;
property wxxy:TpvVector4 read GetWXXY;
property wxxz:TpvVector4 read GetWXXZ;
property wxy:TpvVector3 read GetWXY write SetWXY;
property wxyw:TpvVector4 read GetWXYW;
property wxyx:TpvVector4 read GetWXYX;
property wxyy:TpvVector4 read GetWXYY;
property wxyz:TpvVector4 read GetWXYZ write SetWXYZ;
property wxz:TpvVector3 read GetWXZ write SetWXZ;
property wxzw:TpvVector4 read GetWXZW;
property wxzx:TpvVector4 read GetWXZX;
property wxzy:TpvVector4 read GetWXZY write SetWXZY;
property wxzz:TpvVector4 read GetWXZZ;
property wy:TpvVector2 read GetWY write SetWY;
property wyw:TpvVector3 read GetWYW;
property wyww:TpvVector4 read GetWYWW;
property wywx:TpvVector4 read GetWYWX;
property wywy:TpvVector4 read GetWYWY;
property wywz:TpvVector4 read GetWYWZ;
property wyx:TpvVector3 read GetWYX write SetWYX;
property wyxw:TpvVector4 read GetWYXW;
property wyxx:TpvVector4 read GetWYXX;
property wyxy:TpvVector4 read GetWYXY;
property wyxz:TpvVector4 read GetWYXZ write SetWYXZ;
property wyy:TpvVector3 read GetWYY;
property wyyw:TpvVector4 read GetWYYW;
property wyyx:TpvVector4 read GetWYYX;
property wyyy:TpvVector4 read GetWYYY;
property wyyz:TpvVector4 read GetWYYZ;
property wyz:TpvVector3 read GetWYZ write SetWYZ;
property wyzw:TpvVector4 read GetWYZW;
property wyzx:TpvVector4 read GetWYZX write SetWYZX;
property wyzy:TpvVector4 read GetWYZY;
property wyzz:TpvVector4 read GetWYZZ;
property wz:TpvVector2 read GetWZ write SetWZ;
property wzw:TpvVector3 read GetWZW;
property wzww:TpvVector4 read GetWZWW;
property wzwx:TpvVector4 read GetWZWX;
property wzwy:TpvVector4 read GetWZWY;
property wzwz:TpvVector4 read GetWZWZ;
property wzx:TpvVector3 read GetWZX write SetWZX;
property wzxw:TpvVector4 read GetWZXW;
property wzxx:TpvVector4 read GetWZXX;
property wzxy:TpvVector4 read GetWZXY write SetWZXY;
property wzxz:TpvVector4 read GetWZXZ;
property wzy:TpvVector3 read GetWZY write SetWZY;
property wzyw:TpvVector4 read GetWZYW;
property wzyx:TpvVector4 read GetWZYX write SetWZYX;
property wzyy:TpvVector4 read GetWZYY;
property wzyz:TpvVector4 read GetWZYZ;
property wzz:TpvVector3 read GetWZZ;
property wzzw:TpvVector4 read GetWZZW;
property wzzx:TpvVector4 read GetWZZX;
property wzzy:TpvVector4 read GetWZZY;
property wzzz:TpvVector4 read GetWZZZ;
property xw:TpvVector2 read GetXW write SetXW;
property xww:TpvVector3 read GetXWW;
property xwww:TpvVector4 read GetXWWW;
property xwwx:TpvVector4 read GetXWWX;
property xwwy:TpvVector4 read GetXWWY;
property xwwz:TpvVector4 read GetXWWZ;
property xwx:TpvVector3 read GetXWX;
property xwxw:TpvVector4 read GetXWXW;
property xwxx:TpvVector4 read GetXWXX;
property xwxy:TpvVector4 read GetXWXY;
property xwxz:TpvVector4 read GetXWXZ;
property xwy:TpvVector3 read GetXWY write SetXWY;
property xwyw:TpvVector4 read GetXWYW;
property xwyx:TpvVector4 read GetXWYX;
property xwyy:TpvVector4 read GetXWYY;
property xwyz:TpvVector4 read GetXWYZ write SetXWYZ;
property xwz:TpvVector3 read GetXWZ write SetXWZ;
property xwzw:TpvVector4 read GetXWZW;
property xwzx:TpvVector4 read GetXWZX;
property xwzy:TpvVector4 read GetXWZY write SetXWZY;
property xwzz:TpvVector4 read GetXWZZ;
property xx:TpvVector2 read GetXX;
property xxw:TpvVector3 read GetXXW;
property xxww:TpvVector4 read GetXXWW;
property xxwx:TpvVector4 read GetXXWX;
property xxwy:TpvVector4 read GetXXWY;
property xxwz:TpvVector4 read GetXXWZ;
property xxx:TpvVector3 read GetXXX;
property xxxw:TpvVector4 read GetXXXW;
property xxxx:TpvVector4 read GetXXXX;
property xxxy:TpvVector4 read GetXXXY;
property xxxz:TpvVector4 read GetXXXZ;
property xxy:TpvVector3 read GetXXY;
property xxyw:TpvVector4 read GetXXYW;
property xxyx:TpvVector4 read GetXXYX;
property xxyy:TpvVector4 read GetXXYY;
property xxyz:TpvVector4 read GetXXYZ;
property xxz:TpvVector3 read GetXXZ;
property xxzw:TpvVector4 read GetXXZW;
property xxzx:TpvVector4 read GetXXZX;
property xxzy:TpvVector4 read GetXXZY;
property xxzz:TpvVector4 read GetXXZZ;
property xy:TpvVector2 read GetXY write SetXY;
property xyw:TpvVector3 read GetXYW write SetXYW;
property xyww:TpvVector4 read GetXYWW;
property xywx:TpvVector4 read GetXYWX;
property xywy:TpvVector4 read GetXYWY;
property xywz:TpvVector4 read GetXYWZ write SetXYWZ;
property xyx:TpvVector3 read GetXYX;
property xyxw:TpvVector4 read GetXYXW;
property xyxx:TpvVector4 read GetXYXX;
property xyxy:TpvVector4 read GetXYXY;
property xyxz:TpvVector4 read GetXYXZ;
property xyy:TpvVector3 read GetXYY;
property xyyw:TpvVector4 read GetXYYW;
property xyyx:TpvVector4 read GetXYYX;
property xyyy:TpvVector4 read GetXYYY;
property xyyz:TpvVector4 read GetXYYZ;
property xyz:TpvVector3 read GetXYZ write SetXYZ;
property xyzw:TpvVector4 read GetXYZW write SetXYZW;
property xyzx:TpvVector4 read GetXYZX;
property xyzy:TpvVector4 read GetXYZY;
property xyzz:TpvVector4 read GetXYZZ;
property xz:TpvVector2 read GetXZ write SetXZ;
property xzw:TpvVector3 read GetXZW write SetXZW;
property xzww:TpvVector4 read GetXZWW;
property xzwx:TpvVector4 read GetXZWX;
property xzwy:TpvVector4 read GetXZWY write SetXZWY;
property xzwz:TpvVector4 read GetXZWZ;
property xzx:TpvVector3 read GetXZX;
property xzxw:TpvVector4 read GetXZXW;
property xzxx:TpvVector4 read GetXZXX;
property xzxy:TpvVector4 read GetXZXY;
property xzxz:TpvVector4 read GetXZXZ;
property xzy:TpvVector3 read GetXZY write SetXZY;
property xzyw:TpvVector4 read GetXZYW write SetXZYW;
property xzyx:TpvVector4 read GetXZYX;
property xzyy:TpvVector4 read GetXZYY;
property xzyz:TpvVector4 read GetXZYZ;
property xzz:TpvVector3 read GetXZZ;
property xzzw:TpvVector4 read GetXZZW;
property xzzx:TpvVector4 read GetXZZX;
property xzzy:TpvVector4 read GetXZZY;
property xzzz:TpvVector4 read GetXZZZ;
property yw:TpvVector2 read GetYW write SetYW;
property yww:TpvVector3 read GetYWW;
property ywww:TpvVector4 read GetYWWW;
property ywwx:TpvVector4 read GetYWWX;
property ywwy:TpvVector4 read GetYWWY;
property ywwz:TpvVector4 read GetYWWZ;
property ywx:TpvVector3 read GetYWX write SetYWX;
property ywxw:TpvVector4 read GetYWXW;
property ywxx:TpvVector4 read GetYWXX;
property ywxy:TpvVector4 read GetYWXY;
property ywxz:TpvVector4 read GetYWXZ write SetYWXZ;
property ywy:TpvVector3 read GetYWY;
property ywyw:TpvVector4 read GetYWYW;
property ywyx:TpvVector4 read GetYWYX;
property ywyy:TpvVector4 read GetYWYY;
property ywyz:TpvVector4 read GetYWYZ;
property ywz:TpvVector3 read GetYWZ write SetYWZ;
property ywzw:TpvVector4 read GetYWZW;
property ywzx:TpvVector4 read GetYWZX write SetYWZX;
property ywzy:TpvVector4 read GetYWZY;
property ywzz:TpvVector4 read GetYWZZ;
property yx:TpvVector2 read GetYX write SetYX;
property yxw:TpvVector3 read GetYXW write SetYXW;
property yxww:TpvVector4 read GetYXWW;
property yxwx:TpvVector4 read GetYXWX;
property yxwy:TpvVector4 read GetYXWY;
property yxwz:TpvVector4 read GetYXWZ write SetYXWZ;
property yxx:TpvVector3 read GetYXX;
property yxxw:TpvVector4 read GetYXXW;
property yxxx:TpvVector4 read GetYXXX;
property yxxy:TpvVector4 read GetYXXY;
property yxxz:TpvVector4 read GetYXXZ;
property yxy:TpvVector3 read GetYXY;
property yxyw:TpvVector4 read GetYXYW;
property yxyx:TpvVector4 read GetYXYX;
property yxyy:TpvVector4 read GetYXYY;
property yxyz:TpvVector4 read GetYXYZ;
property yxz:TpvVector3 read GetYXZ write SetYXZ;
property yxzw:TpvVector4 read GetYXZW write SetYXZW;
property yxzx:TpvVector4 read GetYXZX;
property yxzy:TpvVector4 read GetYXZY;
property yxzz:TpvVector4 read GetYXZZ;
property yy:TpvVector2 read GetYY;
property yyw:TpvVector3 read GetYYW;
property yyww:TpvVector4 read GetYYWW;
property yywx:TpvVector4 read GetYYWX;
property yywy:TpvVector4 read GetYYWY;
property yywz:TpvVector4 read GetYYWZ;
property yyx:TpvVector3 read GetYYX;
property yyxw:TpvVector4 read GetYYXW;
property yyxx:TpvVector4 read GetYYXX;
property yyxy:TpvVector4 read GetYYXY;
property yyxz:TpvVector4 read GetYYXZ;
property yyy:TpvVector3 read GetYYY;
property yyyw:TpvVector4 read GetYYYW;
property yyyx:TpvVector4 read GetYYYX;
property yyyy:TpvVector4 read GetYYYY;
property yyyz:TpvVector4 read GetYYYZ;
property yyz:TpvVector3 read GetYYZ;
property yyzw:TpvVector4 read GetYYZW;
property yyzx:TpvVector4 read GetYYZX;
property yyzy:TpvVector4 read GetYYZY;
property yyzz:TpvVector4 read GetYYZZ;
property yz:TpvVector2 read GetYZ write SetYZ;
property yzw:TpvVector3 read GetYZW write SetYZW;
property yzww:TpvVector4 read GetYZWW;
property yzwx:TpvVector4 read GetYZWX write SetYZWX;
property yzwy:TpvVector4 read GetYZWY;
property yzwz:TpvVector4 read GetYZWZ;
property yzx:TpvVector3 read GetYZX write SetYZX;
property yzxw:TpvVector4 read GetYZXW write SetYZXW;
property yzxx:TpvVector4 read GetYZXX;
property yzxy:TpvVector4 read GetYZXY;
property yzxz:TpvVector4 read GetYZXZ;
property yzy:TpvVector3 read GetYZY;
property yzyw:TpvVector4 read GetYZYW;
property yzyx:TpvVector4 read GetYZYX;
property yzyy:TpvVector4 read GetYZYY;
property yzyz:TpvVector4 read GetYZYZ;
property yzz:TpvVector3 read GetYZZ;
property yzzw:TpvVector4 read GetYZZW;
property yzzx:TpvVector4 read GetYZZX;
property yzzy:TpvVector4 read GetYZZY;
property yzzz:TpvVector4 read GetYZZZ;
property zw:TpvVector2 read GetZW write SetZW;
property zww:TpvVector3 read GetZWW;
property zwww:TpvVector4 read GetZWWW;
property zwwx:TpvVector4 read GetZWWX;
property zwwy:TpvVector4 read GetZWWY;
property zwwz:TpvVector4 read GetZWWZ;
property zwx:TpvVector3 read GetZWX write SetZWX;
property zwxw:TpvVector4 read GetZWXW;
property zwxx:TpvVector4 read GetZWXX;
property zwxy:TpvVector4 read GetZWXY write SetZWXY;
property zwxz:TpvVector4 read GetZWXZ;
property zwy:TpvVector3 read GetZWY write SetZWY;
property zwyw:TpvVector4 read GetZWYW;
property zwyx:TpvVector4 read GetZWYX write SetZWYX;
property zwyy:TpvVector4 read GetZWYY;
property zwyz:TpvVector4 read GetZWYZ;
property zwz:TpvVector3 read GetZWZ;
property zwzw:TpvVector4 read GetZWZW;
property zwzx:TpvVector4 read GetZWZX;
property zwzy:TpvVector4 read GetZWZY;
property zwzz:TpvVector4 read GetZWZZ;
property zx:TpvVector2 read GetZX write SetZX;
property zxw:TpvVector3 read GetZXW write SetZXW;
property zxww:TpvVector4 read GetZXWW;
property zxwx:TpvVector4 read GetZXWX;
property zxwy:TpvVector4 read GetZXWY write SetZXWY;
property zxwz:TpvVector4 read GetZXWZ;
property zxx:TpvVector3 read GetZXX;
property zxxw:TpvVector4 read GetZXXW;
property zxxx:TpvVector4 read GetZXXX;
property zxxy:TpvVector4 read GetZXXY;
property zxxz:TpvVector4 read GetZXXZ;
property zxy:TpvVector3 read GetZXY write SetZXY;
property zxyw:TpvVector4 read GetZXYW write SetZXYW;
property zxyx:TpvVector4 read GetZXYX;
property zxyy:TpvVector4 read GetZXYY;
property zxyz:TpvVector4 read GetZXYZ;
property zxz:TpvVector3 read GetZXZ;
property zxzw:TpvVector4 read GetZXZW;
property zxzx:TpvVector4 read GetZXZX;
property zxzy:TpvVector4 read GetZXZY;
property zxzz:TpvVector4 read GetZXZZ;
property zy:TpvVector2 read GetZY write SetZY;
property zyw:TpvVector3 read GetZYW write SetZYW;
property zyww:TpvVector4 read GetZYWW;
property zywx:TpvVector4 read GetZYWX write SetZYWX;
property zywy:TpvVector4 read GetZYWY;
property zywz:TpvVector4 read GetZYWZ;
property zyx:TpvVector3 read GetZYX write SetZYX;
property zyxw:TpvVector4 read GetZYXW write SetZYXW;
property zyxx:TpvVector4 read GetZYXX;
property zyxy:TpvVector4 read GetZYXY;
property zyxz:TpvVector4 read GetZYXZ;
property zyy:TpvVector3 read GetZYY;
property zyyw:TpvVector4 read GetZYYW;
property zyyx:TpvVector4 read GetZYYX;
property zyyy:TpvVector4 read GetZYYY;
property zyyz:TpvVector4 read GetZYYZ;
property zyz:TpvVector3 read GetZYZ;
property zyzw:TpvVector4 read GetZYZW;
property zyzx:TpvVector4 read GetZYZX;
property zyzy:TpvVector4 read GetZYZY;
property zyzz:TpvVector4 read GetZYZZ;
property zz:TpvVector2 read GetZZ;
property zzw:TpvVector3 read GetZZW;
property zzww:TpvVector4 read GetZZWW;
property zzwx:TpvVector4 read GetZZWX;
property zzwy:TpvVector4 read GetZZWY;
property zzwz:TpvVector4 read GetZZWZ;
property zzx:TpvVector3 read GetZZX;
property zzxw:TpvVector4 read GetZZXW;
property zzxx:TpvVector4 read GetZZXX;
property zzxy:TpvVector4 read GetZZXY;
property zzxz:TpvVector4 read GetZZXZ;
property zzy:TpvVector3 read GetZZY;
property zzyw:TpvVector4 read GetZZYW;
property zzyx:TpvVector4 read GetZZYX;
property zzyy:TpvVector4 read GetZZYY;
property zzyz:TpvVector4 read GetZZYZ;
property zzz:TpvVector3 read GetZZZ;
property zzzw:TpvVector4 read GetZZZW;
property zzzx:TpvVector4 read GetZZZX;
property zzzy:TpvVector4 read GetZZZY;
property zzzz:TpvVector4 read GetZZZZ;
